// Prompt expansion map: turns each DNA chip / option into a rich prompt phrase
// suitable for SDXL / Flux / Chroma / Qwen / IPAdapter workflows.
// Structure: PROMPT_MAP[sectionKey][fieldKey][optionValue] = "detailed phrase"
// Anything not mapped falls back to the raw value.

export const PROMPT_MAP = {
  identity: {
    gender: {
      "female": "adult woman, feminine features",
      "male": "adult man, masculine features",
      "non-binary": "androgynous adult, gender-fluid features",
      "androgynous": "androgynous beauty, ambiguous gender presentation",
    },
    ethnicity: {
      "latina": "gorgeous Latina woman, warm honey-tanned skin, dark expressive eyes, sultry Latin features",
      "mexican": "beautiful Mexican woman, warm caramel skin, dark eyes, traditional Latin beauty",
      "brazilian": "stunning Brazilian woman, sun-kissed golden skin, athletic curves, sultry Latin features",
      "colombian": "sultry Colombian woman, olive skin, dark eyes, voluptuous Latin body",
      "puerto rican": "beautiful Puerto Rican woman, caramel skin, dark curly hair, Latin sensuality",
      "cuban": "gorgeous Cuban woman, olive skin, dark eyes, curvy Latin figure",
      "dominican": "stunning Dominican woman, rich caramel skin, curly hair, curvy Caribbean beauty",
      "venezuelan": "elegant Venezuelan woman, olive skin, refined Latin features",
      "argentinian": "beautiful Argentinian woman, European-Latin blend, olive skin",
      "peruvian": "beautiful Peruvian woman, warm indigenous features, tan skin",
      "east asian": "beautiful East Asian woman, porcelain skin, dark almond eyes, delicate features",
      "japanese": "beautiful Japanese woman, delicate porcelain skin, dark almond eyes, silky black hair",
      "korean": "beautiful Korean woman, flawless smooth skin, dark almond eyes, elegant features",
      "chinese": "beautiful Chinese woman, porcelain skin, dark eyes, elegant Asian features",
      "vietnamese": "beautiful Vietnamese woman, warm golden skin, dark expressive eyes",
      "thai": "beautiful Thai woman, warm golden skin, exotic Southeast Asian features",
      "filipina": "gorgeous Filipina woman, warm tan skin, dark expressive eyes, tropical beauty",
      "indonesian": "beautiful Indonesian woman, warm tan skin, exotic tropical features",
      "cambodian": "beautiful Cambodian woman, warm bronze skin, exotic features",
      "south asian": "beautiful South Asian woman, warm bronze skin, dark eyes, exotic features",
      "indian": "beautiful Indian woman, warm bronze skin, dark expressive kohl-lined eyes, long dark hair",
      "pakistani": "beautiful Pakistani woman, warm bronze skin, striking dark features",
      "bangladeshi": "beautiful Bangladeshi woman, warm caramel skin, dark eyes",
      "sri lankan": "beautiful Sri Lankan woman, warm bronze skin, dark eyes, exotic features",
      "black": "gorgeous Black woman, rich dark skin, striking African features",
      "african american": "stunning African American woman, beautiful dark skin, natural features",
      "ebony": "gorgeous ebony woman, rich chocolate skin, striking beautiful features, African goddess",
      "afro-caribbean": "beautiful Afro-Caribbean woman, rich dark skin, natural coily hair",
      "nigerian": "stunning Nigerian woman, deep dark chocolate skin, striking West African features",
      "ethiopian": "stunning Ethiopian woman, warm bronze skin, elegant East African features",
      "somali": "beautiful Somali woman, warm dark skin, elegant East African features, high cheekbones",
      "white": "beautiful Caucasian woman, fair skin, classical European features",
      "caucasian": "beautiful Caucasian woman, fair skin, classic Western features",
      "european": "beautiful European woman, refined features, fair skin",
      "british": "beautiful British woman, pale porcelain skin, classic English rose features",
      "french": "gorgeous French woman, elegant refined features, effortless Parisian beauty",
      "german": "beautiful German woman, fair skin, striking Nordic-European features",
      "italian": "stunning Italian woman, olive Mediterranean skin, dark eyes, classic Italian beauty",
      "spanish": "beautiful Spanish woman, olive Mediterranean skin, dark passionate eyes",
      "irish": "beautiful Irish woman, pale porcelain skin, freckles, red hair, striking green eyes",
      "russian": "stunning Russian woman, fair skin, striking cold Slavic beauty, sharp cheekbones",
      "polish": "beautiful Polish woman, fair skin, Slavic features",
      "nordic": "stunning Nordic goddess, ivory pale skin, ice-blue eyes, platinum blonde hair",
      "scandinavian": "beautiful Scandinavian woman, ivory skin, ice-blue eyes, blonde hair",
      "swedish": "beautiful Swedish woman, pale porcelain skin, blonde hair, blue eyes",
      "norwegian": "beautiful Norwegian woman, pale skin, blonde hair, striking Nordic features",
      "icelandic": "beautiful Icelandic woman, ivory skin, platinum blonde, glacial beauty",
      "middle eastern": "gorgeous Middle Eastern woman, warm olive skin, dark expressive kohl-lined eyes, thick dark hair",
      "arab": "stunning Arab woman, olive skin, dark almond eyes, exotic Middle Eastern beauty",
      "persian": "stunning Persian woman, warm olive skin, striking dark eyes, thick hair, refined features",
      "turkish": "beautiful Turkish woman, olive skin, dark eyes, striking features",
      "lebanese": "gorgeous Lebanese woman, olive Mediterranean skin, striking dark eyes",
      "egyptian": "stunning Egyptian woman, warm bronze skin, dark kohl-lined eyes, Cleopatra features",
      "moroccan": "beautiful Moroccan woman, warm olive skin, exotic North African features",
      "israeli": "beautiful Israeli woman, olive Mediterranean skin, dark eyes",
      "polynesian": "gorgeous Polynesian woman, warm caramel skin, tropical island beauty, thick dark hair",
      "hawaiian": "beautiful Hawaiian woman, warm tan skin, tropical island beauty",
      "samoan": "stunning Samoan woman, warm caramel skin, curvy Polynesian body, traditional beauty",
      "maori": "beautiful Maori woman, warm bronze skin, traditional Polynesian features",
      "native american": "beautiful Native American woman, warm bronze skin, striking indigenous features",
      "indigenous": "beautiful indigenous woman, warm bronze skin, traditional features",
      "mixed": "beautiful mixed-race woman, exotic blended features, warm complexion",
      "blasian": "gorgeous mixed Black and Asian woman, unique blended features, warm skin",
      "afro-latina": "stunning Afro-Latina woman, rich caramel skin, curly hair, curvy Latin body",
      "eurasian": "beautiful Eurasian woman, exotic mixed European-Asian features",
      "mulatto": "gorgeous mixed-race woman, caramel skin, unique blended features",
      "mestiza": "beautiful mestiza woman, blended indigenous and European features, warm skin",
      "creole": "beautiful Creole woman, exotic blended features, warm caramel skin",
      "amerasian": "beautiful mixed American and Asian woman, blended features",
      "mediterranean": "beautiful Mediterranean woman, olive skin, dark eyes, classic Southern European beauty",
      "greek": "stunning Greek woman, olive skin, classical Mediterranean features",
    },
    archetype: {
      "girl next door": "wholesome girl-next-door charm, natural approachable beauty, warm smile",
      "femme fatale": "seductive femme fatale, dangerous allure, mysterious dark energy, dominant presence",
      "warrior": "fierce warrior woman, battle-ready confident stance, powerful",
      "pirate": "sexy pirate queen, tattered corset, hoop earrings, sword at hip, weathered beauty",
      "cyberpunk": "cyberpunk cyber-goth aesthetic, neon accents, futuristic tech, edgy",
      "goth": "dark gothic aesthetic, black lipstick, pale skin, brooding beauty, alternative style",
      "cottagecore": "soft cottagecore aesthetic, romantic pastoral, flowing dresses, natural",
      "athlete": "athletic fitness-model physique, defined muscles, healthy glow, confident",
      "queen": "regal queenly presence, elegant powerful, refined beauty, commanding",
      "bombshell": "classic Hollywood bombshell, blonde ambition, curvy glamour, red lips",
      "amazonian": "tall statuesque amazonian goddess, powerful strong body, commanding presence",
    },
  },

  physique: {
    body_type: {
      "slim": "slim slender build, delicate frame",
      "athletic": "athletic toned build, defined muscles, fit physique",
      "curvy": "curvy voluptuous figure, generous curves, feminine proportions",
      "voluptuous": "extremely voluptuous body, abundant curves, thick and luscious",
      "plus size": "beautiful plus-size BBW figure, thick voluptuous body, generous curves",
      "hourglass": "perfect hourglass figure, cinched narrow waist, ample bust and hips, dramatic curves",
      "pear": "pear-shaped figure, narrow waist, generous hips and thighs, prominent rear",
      "apple": "apple-shaped figure, fuller midsection, curvy bust",
      "bombshell": "classic bombshell curves, dramatic hourglass, extreme feminine proportions",
      "amazonian": "tall statuesque amazonian body, long powerful limbs",
    },
    bust: {
      "flat": "flat chest, small AA cup, boyish chest",
      "small": "small perky A-cup breasts",
      "medium": "medium B-C cup natural breasts",
      "large": "large heavy D-cup breasts, prominent cleavage",
      "very large": "very large heavy DD-cup breasts, massive cleavage",
      "huge": "huge massive G-cup breasts, enormous cleavage, spilling out, gravity-affected",
      "enormous": "enormous H-cup+ tits, gigantic breasts, dramatic overflowing cleavage",
      "hyper": "hyper-inflated impossibly huge breasts, cartoonishly enormous tits, gravity-defying",
    },
    bust_shape: {
      "natural": "natural sagging teardrop breasts, realistic weight",
      "perky": "perky firm upturned breasts, youthful",
      "round": "perfectly round full breasts, spherical",
      "teardrop": "beautiful teardrop-shaped natural breasts",
      "athletic": "small athletic firm breasts, muscled chest",
      "augmented": "obviously fake augmented breasts, round implants, firm and high",
      "gravity-defying": "impossibly gravity-defying breasts, unnaturally high and firm",
    },
    butt: {
      "flat": "flat pancake ass, small buttocks",
      "small": "small tight ass, petite butt",
      "toned": "toned firm athletic ass, sculpted glutes",
      "round": "round shapely ass, perfectly curved buttocks",
      "bubble": "gorgeous bubble butt, perky round rear, prominent shelf ass",
      "large": "large juicy ass, big round buttocks, prominent rear",
      "very large": "very large jiggly ass, massive round butt",
      "huge": "huge enormous ass, gigantic buttocks, PAWG rear",
      "hyper": "hyper-sized cartoonishly enormous ass, impossibly huge butt, extreme bubble",
    },
    thighs: {
      "slim": "slim slender thighs",
      "toned": "toned athletic thighs, defined muscles",
      "athletic": "athletic muscled thighs, powerful legs",
      "thick": "thick juicy thighs, meaty legs, curvy",
      "very thick": "extremely thick thighs, huge meaty juicy legs, thigh gap gone",
      "massive": "massive tree-trunk thighs, cartoonishly thick legs",
    },
    hips: {
      "narrow": "narrow slim hips",
      "average": "average natural hips",
      "wide": "wide childbearing hips, curvy pelvis",
      "very wide": "extremely wide hips, dramatic hip-to-waist ratio",
      "extreme": "impossibly wide hips, exaggerated pelvis, extreme hourglass",
    },
    waist: {
      "thick": "thick natural waist",
      "average": "average natural waist",
      "slim": "slim narrow waist",
      "cinched": "cinched corseted narrow waist, dramatic hourglass",
      "tiny": "impossibly tiny waist, wasp waist",
      "wasp-thin": "wasp-thin corseted waist, cartoonish hourglass",
    },
    shoulders: {
      "narrow": "narrow feminine shoulders",
      "broad": "broad shoulders, powerful build",
      "athletic": "athletic sculpted shoulders",
    },
    legs: {
      "short": "short legs",
      "average": "average legs",
      "long": "long shapely legs",
      "endless": "impossibly long endless legs, dramatic leg length",
    },
  },

  face: {
    eye_shape: {
      "almond": "beautiful almond-shaped eyes, elegant eye shape",
      "round": "large round doe eyes, big innocent eyes",
      "hooded": "sexy hooded bedroom eyes, sultry heavy lids",
      "monolid": "elegant monolid Asian eyes",
      "upturned": "cat-like upturned eyes, feline shape",
      "downturned": "soft downturned eyes, puppy-dog gaze",
    },
    eye_color: {
      "deep brown": "deep chocolate brown eyes",
      "hazel": "warm hazel eyes with green flecks",
      "green": "striking emerald green eyes",
      "blue": "piercing crystal blue eyes",
      "grey": "cold steel grey eyes",
      "amber": "unusual amber golden eyes",
      "violet": "rare stunning violet purple eyes",
    },
    jawline: {
      "soft": "soft rounded jawline, gentle feminine face",
      "defined": "defined sculpted jawline",
      "angular": "sharp angular jawline, striking features",
      "square": "strong square jawline",
      "heart-shaped": "delicate heart-shaped face, pointed chin",
    },
    lips: {
      "thin": "thin delicate lips",
      "medium": "medium natural lips",
      "full": "full plump pouty lips, luscious pillowy lips",
      "pouty": "sexy pouty pillowy lips, DSL dick-sucking lips",
      "bow-shaped": "perfect cupid's bow lips, dainty bow shape",
    },
    expression: {
      "neutral": "neutral relaxed expression",
      "smirk": "cocky playful smirk, mischievous half-smile",
      "smile": "warm genuine smile, bright expression",
      "serious": "intense serious expression, focused",
      "sultry": "sultry seductive expression, half-lidded bedroom eyes, parted lips, come-hither gaze",
      "laughing": "genuine laugh, joyful expression",
    },
  },

  hair: {
    style: {
      "straight": "sleek straight hair",
      "wavy": "loose beachy waves, tousled wavy hair",
      "curly": "bouncy defined curls, curly hair",
      "coily": "natural coily hair, defined coils",
      "braids": "intricate braided hair, box braids",
      "updo": "elegant updo hairstyle, hair swept up",
      "ponytail": "sexy high ponytail, hair pulled back",
      "messy": "messy tousled bedhead hair, disheveled",
    },
    length: {
      "pixie": "short pixie cut",
      "short bob": "chic short bob haircut",
      "shoulder": "shoulder-length hair",
      "long": "long flowing hair, cascading down back",
      "waist-length": "extremely long waist-length hair, dramatic length",
    },
    color: {
      "jet black": "jet black raven hair, glossy dark",
      "chestnut": "rich chestnut brown hair with warm highlights",
      "auburn": "auburn hair with red and copper highlights",
      "fiery red": "fiery vibrant red hair, striking crimson",
      "platinum blonde": "icy platinum blonde hair",
      "honey blonde": "warm honey blonde hair with golden highlights",
      "silver": "silver gray hair, striking metallic tone",
      "raven": "glossy raven black hair",
      "ombre": "dramatic ombre hair, dark roots fading to light ends",
    },
  },

  skin: {
    tone: {
      "porcelain": "flawless porcelain pale skin, ivory complexion",
      "fair": "fair light skin",
      "olive": "warm olive Mediterranean skin",
      "tan": "sun-kissed tan skin, golden complexion",
      "bronze": "rich bronze skin, deep tan",
      "dark brown": "rich dark brown skin, deep melanin",
      "ebony": "deep ebony skin, rich chocolate complexion",
    },
    texture: {
      "smooth": "flawless smooth skin, poreless complexion",
      "natural pores": "realistic skin with natural pores and texture, high detail",
      "textured": "highly textured skin with visible pores, freckles, and imperfections",
      "matte": "matte velvety skin, no shine",
      "dewy": "dewy glowing skin, healthy sheen, luminous",
      "oiled": "oiled slick glistening skin, wet shiny body oil",
      "sweat-glistening": "sweat-glistening skin, beads of sweat, moist glow, wet body",
    },
    freckles: {
      "light": "light delicate freckles across nose",
      "scattered": "scattered natural freckles across face and shoulders",
      "heavy": "heavy freckles covering face and body, prominent freckling",
    },
  },

  intimate: {
    pubic_hair: {
      "hairless": "completely hairless smooth bare pussy, shaved bald mound",
      "shaved smooth": "freshly shaved smooth pussy, no pubic hair, silky bare mound",
      "stubble": "light stubble regrowth on pubic mound, prickly short pubes",
      "trimmed": "neatly trimmed short pubic hair, well-groomed bush",
      "landing strip": "tidy vertical landing strip of pubic hair, groomed",
      "natural bush": "natural full untamed pubic hair, unshaved bush",
      "hairy": "hairy unshaved pussy, thick pubic hair covering mound",
      "very hairy": "very hairy dense bush, thick full pubic hair, completely unshaved",
      "wild bush": "wild unkempt overgrown pubic bush, big furry unshaved 70s bush",
      "heart-shaped": "cute heart-shaped landing strip of pubic hair",
    },
    pussy: {
      "closed": "tight closed pussy, small labia tucked in neatly",
      "small labia": "small tight pussy lips, tucked inner labia",
      "prominent labia": "prominent meaty labia, outer lips fully visible and protruding",
      "puffy": "puffy plump swollen pussy mound, thick meaty vulva",
      "innie": "innie pussy, labia neatly tucked inside, cameltoe",
      "outie": "outie pussy, protruding meaty labia, hanging inner lips, full prominent vulva",
      "meaty": "meaty thick labia, prominent full vulva, engorged lips",
      "tight": "very tight small pussy, delicate opening",
      "spread": "spread open pussy, exposed labia, vaginal opening visible, everything on display",
      "wet": "wet dripping pussy, glistening arousal fluids, moist labia, aroused and dripping",
    },
    clit: {
      "subtle": "subtle hidden clit under hood",
      "prominent": "prominent engorged aroused clit, visible clitoris",
      "large": "large protruding clit, big engorged clitoris, prominent nub",
      "pierced": "clit hood piercing, jeweled clitoris piercing",
    },
    asshole: {
      "tight": "tight small puckered asshole",
      "visible": "visible tight asshole, exposed anus between cheeks",
      "puckered": "puckered tight pink asshole",
      "trimmed": "clean trimmed asshole, no hair around anus",
      "hairy": "hairy asshole, dense pubic hair around anus, unshaven",
      "bleached": "bleached pink clean asshole, perfectly light and hairless",
      "pierced": "pierced perineum, jeweled anus piercing",
      "spread": "spread wide open asshole, gaping anus, held open",
    },
    nipples: {
      "soft": "soft relaxed nipples",
      "erect": "hard erect stiff nipples, pointing and aroused, poking out",
      "inverted": "inverted shy nipples",
      "small": "small delicate nipples",
      "large": "very large protruding thick nipples, prominent tips",
      "puffy": "puffy dome nipples, plump swollen nipple areolas",
      "pierced": "nipple barbell piercings, jeweled nipple rings, both pierced",
    },
    areolas: {
      "small pale": "small pale pink areolas",
      "medium pink": "medium rosy pink areolas",
      "large brown": "large wide brown areolas, prominent dark areolas",
      "very large dark": "very large dark chocolate brown areolas, huge dinner-plate areolas covering breast",
      "puffy dome": "puffy dome-shaped swollen areolas, plump raised mounds",
    },
    body_hair: {
      "light peach fuzz": "light peach fuzz body hair, natural fine hair",
      "moderate": "moderate natural body hair, arms and legs unshaved",
      "heavy": "heavy body hair, hirsute unshaved arms, legs, and stomach",
      "natural": "natural realistic body hair, unshaved",
      "unshaven armpits": "hairy unshaven armpits, thick underarm hair visible",
    },
    piercings: {
      "nipple": "nipple barbell piercings, jeweled nipple rings",
      "navel": "belly button navel piercing, jeweled",
      "nose": "nose stud piercing",
      "septum": "septum ring piercing",
      "tongue": "tongue barbell piercing",
      "clit hood": "clit hood piercing, jeweled hood ring",
      "labia": "labia piercings, jeweled outer lips",
      "multi": "multiple body piercings, nipples, navel, clit hood, all jeweled",
    },
  },

  wardrobe: {
    outfit_preset: {
      "nude": "completely nude, fully naked, bare exposed body, no clothing",
      "topless": "topless, bare breasts fully exposed, no top on",
      "bottomless": "bottomless, wearing only a top, no pants or panties, pussy exposed",
      "boudoir lingerie": "elegant boudoir lingerie set, lace and satin, intricate details",
      "sheer negligee": "sheer see-through negligee, transparent lingerie revealing everything underneath",
      "silk robe open": "silk robe hanging open loosely, nothing underneath, breasts and body visible",
      "wet t-shirt": "soaked wet t-shirt clinging to nipples, transparent when wet, no bra",
      "bikini": "sexy bikini set, string bikini top and bottom",
      "micro bikini": "extreme micro bikini, tiny strings barely covering, most of body exposed",
      "string bikini": "string bikini, thin ties, minimal coverage",
      "sexy schoolgirl": "sexy schoolgirl outfit, plaid mini skirt, white blouse tied at midriff, knee-high socks, mary jane shoes",
      "naughty nurse": "sexy nurse costume, unbuttoned white uniform showing cleavage, red cross, white stockings and heels",
      "french maid": "sexy french maid costume, black and white ruffled dress, mini skirt, fishnet stockings, apron, feather duster",
      "playboy bunny": "Playboy bunny costume, satin corset bodice, bunny ears, fluffy cotton tail, fishnet stockings, black stilettos",
      "showgirl": "Las Vegas showgirl costume, sequined bodysuit, huge feathered headdress, feather fans, high heels",
      "pole dancer": "sexy pole dancer outfit, tiny sequined bikini, stripper heels, oiled body",
      "gogo dancer": "gogo dancer outfit, metallic mini dress, go-go boots",
      "stripper": "stripper outfit, thigh-high stripper heels, tiny thong, tasseled pasties",
      "cheerleader": "sexy cheerleader uniform, tiny pleated skirt, cropped top, sneakers, pom-poms",
      "dominatrix": "dominatrix in leather, tight leather corset, whip in hand, thigh-high leather boots, latex gloves",
      "leather mistress": "leather mistress outfit, studded leather bodysuit, collar and cuffs, riding crop",
      "latex catsuit": "shiny black latex catsuit, skin-tight second-skin latex bodysuit, glossy zipper up front",
      "kinky harness": "black leather harness across body, strappy fetish gear",
      "shibari rope": "intricate Japanese shibari rope bondage, red rope wrapped around body, kinbaku ties, breasts squeezed by rope",
      "fetish gimp": "fetish gimp suit, leather hood, zipper mouth, full body latex",
      "secretary unbuttoned": "sexy secretary outfit, tight pencil skirt, blouse unbuttoned showing cleavage, glasses, hair in a bun",
      "librarian undone": "naughty librarian outfit, cardigan falling off shoulder, glasses on tip of nose, tight skirt, hair coming undone",
      "biker chick": "biker chick outfit, leather jacket, tiny denim shorts, ripped fishnets, heavy boots",
      "cowgirl chaps": "sexy cowgirl outfit, leather chaps, denim shorts, cowboy boots, plaid shirt tied at midriff, hat",
      "cop uniform undone": "sexy cop outfit unbuttoned, tight blue uniform shirt open, mini skirt, handcuffs, black stockings",
      "flight attendant undone": "sexy flight attendant outfit undone, tight blazer open, mini skirt, stockings, heels",
      "cocktail dress": "elegant tight cocktail dress, plunging neckline, form-fitting",
      "evening gown slit": "glamorous evening gown with high thigh slit, formal red carpet dress",
      "backless red carpet": "backless red carpet gown, plunging back, full-length dress",
      "club outfit": "sexy nightclub outfit, tiny minidress, stiletto heels",
      "yoga wear": "form-fitting yoga wear, sports bra and yoga pants, athletic",
      "gym set": "matching gym set, sports bra and biker shorts, sweaty workout",
      "sports bra and shorts": "tight sports bra and tiny running shorts, athletic",
      "cheerleader off-duty": "off-duty cheerleader, cropped hoodie, tiny booty shorts, sneakers",
      "streetwear": "trendy streetwear, oversized hoodie, tight jeans, sneakers",
      "casual home": "casual at-home outfit, oversized tee, no bra",
      "just a shirt": "wearing only a large button-down shirt, buttons undone, one shoulder off, nothing underneath",
      "boyfriend's shirt": "wearing only an oversized men's dress shirt, buttons open showing cleavage and panties",
      "just panties": "wearing only tiny panties, otherwise fully nude, topless with panties",
    },
    top: {
      "none": "no top, bare chest, topless",
      "sheer top": "sheer see-through top, transparent fabric showing nipples underneath",
      "mesh top": "black mesh see-through top, fishnet fabric",
      "lace bralette": "delicate lace bralette, semi-sheer",
      "bikini top": "string bikini top",
      "corset": "tight-laced corset pushing up breasts, cinched",
      "bustier": "sexy bustier pushing up cleavage",
      "crop top": "tiny crop top exposing midriff",
      "backless top": "backless top exposing full back",
      "keyhole top": "keyhole cutout top showing cleavage",
      "halter": "halter top, tied behind neck",
      "tube top": "tight tube top, strapless",
      "strapless": "strapless top",
      "wet t-shirt": "wet see-through t-shirt clinging to erect nipples",
      "unbuttoned blouse": "blouse completely unbuttoned, hanging open exposing bra and cleavage",
      "ripped shirt": "torn ripped shirt exposing breasts",
      "nipple pasties": "only tiny nipple pasties covering nipples, otherwise topless",
      "leather harness": "black leather harness across chest, straps between breasts",
      "cage bra": "cage-style strappy leather bra, decorative straps",
      "chainmail top": "chainmail metal top, silver mesh armor",
    },
    bottom: {
      "none": "no bottoms, bottomless, pussy exposed",
      "micro-mini skirt": "extreme micro-mini skirt barely covering, upskirt visible",
      "pencil skirt": "tight pencil skirt hugging hips and thighs",
      "leather skirt": "tight black leather mini skirt",
      "school skirt": "pleated plaid school skirt",
      "denim shorts": "tiny cutoff denim shorts",
      "hot pants": "tiny hot pants, spandex",
      "booty shorts": "tiny booty shorts riding up, ass cheeks peeking out",
      "yoga pants": "form-fitting yoga pants, hugging every curve",
      "latex leggings": "shiny black latex leggings, second-skin",
      "wet look pants": "shiny wet-look black pants",
      "cutoff jeans": "cutoff denim jean shorts, frayed hem",
      "chaps": "leather chaps, ass and pussy exposed",
      "fishnet stockings": "black fishnet stockings, sexy legwear",
      "garter belt": "black garter belt holding up stockings",
      "thigh-high stockings": "thigh-high stockings with lace tops",
    },
    underwear: {
      "none": "no panties, bottomless underneath",
      "thong": "tiny string thong, T-back",
      "g-string": "g-string barely-there panties",
      "lace panties": "delicate lace panties",
      "sheer panties": "sheer see-through panties revealing everything",
      "crotchless": "crotchless panties, pussy exposed while wearing",
      "microkini": "extreme microkini panties, tiny strings",
      "boy shorts": "cheeky boy short panties",
      "high-waist briefs": "high-waisted retro briefs",
      "teddy": "sexy lingerie teddy bodysuit",
      "babydoll": "sheer babydoll lingerie, flowing sheer top",
      "chemise": "silk chemise slip lingerie",
      "bodysuit": "tight lingerie bodysuit",
      "mesh bodysuit": "sheer mesh bodysuit revealing everything underneath",
      "corset with garters": "corset with attached garter straps and stockings",
      "harness lingerie": "strappy harness lingerie with garter belt",
      "leather harness": "black leather body harness",
      "bikini set": "matching bikini set",
    },
    footwear: {
      "barefoot": "barefoot, bare feet",
      "stiletto heels": "tall stiletto heels, pointed toe",
      "stripper heels": "extreme clear stripper heels, 8-inch platforms",
      "thigh-high boots": "black thigh-high leather boots, stiletto heels",
      "over-the-knee boots": "over-the-knee black boots",
      "ankle boots": "ankle boots, block heel",
      "combat boots": "chunky combat boots",
      "sneakers": "trendy white sneakers",
      "platform heels": "tall chunky platform heels",
      "sandals": "strappy sandals",
      "kitten heels": "low kitten heels",
      "cowgirl boots": "brown cowgirl boots",
    },
    accessories: {
      "choker": "sexy black choker necklace",
      "leather collar": "leather collar with D-ring",
      "leash": "leather collar and leash, held submissively",
      "handcuffs": "metal handcuffs, wrists bound",
      "gloves": "elbow-length gloves",
      "opera gloves": "long black opera gloves",
      "fishnet gloves": "fishnet gloves",
      "garters": "garter belt with straps down thighs",
      "stockings": "sheer thigh-high stockings",
      "veil": "sheer veil over face",
      "cat ears": "cute cat ears headband",
      "bunny ears": "playboy bunny ears headband",
      "devil horns": "sexy red devil horns",
      "angel wings": "white feather angel wings",
      "sunglasses": "designer sunglasses",
      "jewelry": "sparkling diamond jewelry",
      "body chain": "gold body chain draped across torso",
      "belly chain": "gold belly chain around waist",
    },
    material: {
      "latex": "shiny wet-look latex fabric, second-skin glossy black",
      "PVC": "shiny PVC vinyl fabric, glossy",
      "wet look": "shiny wet-look glossy fabric",
      "sheer mesh": "transparent sheer mesh fabric revealing skin underneath",
      "fishnet": "black fishnet mesh fabric",
      "chainmail": "silver metallic chainmail fabric",
      "leather": "black leather, glossy grain",
      "silk": "smooth silk fabric, luxurious sheen",
      "satin": "shiny satin fabric",
      "lace": "delicate intricate lace",
      "velvet": "plush velvet fabric",
    },
    state: {
      "one strap down": "one shoulder strap slipped down, off shoulder",
      "top pulled down": "top pulled down exposing breasts, nipples out",
      "shirt open": "shirt fully open, hanging loose exposing body",
      "unbuttoned": "buttons undone, top hanging open",
      "unzipped": "zipper down, opening exposing skin underneath",
      "panties pulled aside": "panties pulled to the side exposing pussy while still worn",
      "riding up": "skirt riding up thighs, panties visible",
      "coming off": "clothes coming off mid-strip, half-removed",
      "ripped": "clothes torn ripped, exposing skin through tears",
      "disheveled": "clothes disheveled, messy, post-sex look",
    },
  },

  pose: {
    action: {
      "standing": "standing upright, natural stance",
      "standing hip out": "standing with hip cocked out to the side, weight on one leg",
      "standing hands on hips": "standing with hands on hips, confident power pose",
      "standing arms up": "standing with arms raised overhead, stretching",
      "standing back arched": "standing with back arched dramatically, chest pushed forward, ass out",
      "standing legs apart": "standing with legs spread wide apart",
      "standing splits": "doing a standing splits, one leg raised high overhead",
      "walking": "walking toward camera, mid-stride",
      "leaning wall": "leaning back against a wall, hip cocked out",
      "leaning forward": "leaning forward toward camera, breasts hanging down and forward",
      "bending over": "bending over from waist, ass raised high, pussy peeking out",
      "sitting legs crossed": "sitting elegantly with legs crossed",
      "sitting legs open": "sitting with legs spread wide open, pussy exposed",
      "sitting reverse chair": "straddling a chair backwards, arms resting on back",
      "sitting on edge": "sitting on the edge, legs dangling",
      "kneeling upright": "kneeling upright on both knees, thighs together",
      "kneeling back arched": "kneeling with back arched dramatically, chest thrust forward, ass raised",
      "kneeling hands floor": "on hands and knees, kneeling with hands on the floor, ass presented",
      "lying back": "lying flat on back, relaxed",
      "lying side": "lying on side, curves accentuated, hip out",
      "lying stomach": "lying on stomach, ass raised, feet kicked up",
      "lying legs spread": "lying on back with legs spread wide open, pussy fully exposed",
      "lying legs up": "lying with legs raised straight up in the air",
      "on back legs up": "on back with legs pulled up to shoulders, ankles by head, pussy fully exposed and vulnerable",
      "all fours": "on all fours on hands and knees, presenting ass",
      "doggy arched": "on all fours with back arched dramatically, ass raised high, pushed out and presenting, ready for doggy style",
      "doggy low": "chest down ass up, face-down doggy position, ass raised high",
      "squatting": "squatting deeply, thighs open",
      "squatting spread": "squatting with legs spread wide, pussy fully exposed and open",
      "squatting deep": "deep asian squat, ass low to ground",
      "over shoulder look": "back to camera looking seductively over shoulder, ass front and center",
      "arched on knees": "kneeling with back arched dramatically, ass raised, chest low, presenting",
      "hands on knees": "bent forward with hands on knees, cleavage exposed",
      "hair flip": "hair flip mid-motion, dynamic movement",
      "dancing": "sensual dancing, mid-movement, hips shaking",
      "reverse view": "back to camera, rear view, ass and back visible",
    },
    angle: {
      "front": "front-facing view, straight on",
      "3/4": "three-quarter angle view",
      "profile": "side profile view",
      "back": "rear view from behind",
      "over-shoulder": "over-the-shoulder view, looking back at camera",
      "from above": "high angle shot from above, looking down",
      "from below": "low angle shot from below, looking up, dramatic perspective",
      "pov": "point of view shot, first person POV",
    },
    distance: {
      "close-up": "extreme close-up shot, tight framing",
      "portrait": "portrait framing, head and shoulders",
      "waist-up": "waist-up framing, upper body",
      "full body": "full body shot, head to feet visible",
      "wide shot": "wide environmental shot, full scene",
      "detail shot": "extreme detail macro shot",
    },
    focus: {
      "face": "camera focused on face, sharp facial focus",
      "body": "focused on the body, showcasing curves",
      "breasts": "camera zoomed on breasts, cleavage focus, tits front and center",
      "butt": "camera focused on ass, rear-view booty focus",
      "hips": "focused on hips and waist",
      "legs": "focused on long legs",
      "feet": "focused on feet",
      "hands": "focused on hands",
    },
    hands: {
      "at sides": "arms relaxed at sides",
      "on hips": "hands on hips",
      "in hair": "hands running through hair, seductive",
      "touching body": "hands seductively touching own body, self-caressing",
      "on breasts": "hands cupping own breasts, groping, squeezing",
      "between legs": "hand between legs, touching pussy, masturbating",
      "gripping something": "gripping something tightly",
      "over head": "arms raised overhead",
      "behind back": "hands clasped behind back, submissive",
      "behind head": "hands behind head, elbows out",
    },
    body_language: {
      "sultry": "sultry seductive body language, dripping sex appeal",
      "confident": "confident powerful stance, dominant energy",
      "playful": "playful flirtatious energy, teasing",
      "sensual": "deeply sensual, oozing sexuality",
      "come-hither": "come-hither expression, beckoning gaze",
      "dominant": "dominant powerful energy, in charge",
      "submissive": "submissive vulnerable energy, obedient posture",
      "teasing": "teasing playful demeanor",
    },
  },

  scenario: {
    cast_size: {
      "solo": "solo scene, alone",
      "duo": "two women together in scene",
      "threesome": "threesome, three people in scene",
      "foursome": "foursome, four people",
      "group": "group scene, multiple people",
      "gangbang": "gangbang scene, one woman surrounded by multiple men",
      "orgy": "full orgy scene, many people",
    },
    cast_type: {
      "twins": "two identical twin sisters, matching appearances, mirror images",
      "identical twins": "identical twin sisters, exactly matching, side by side",
      "sisters": "two sisters together, family resemblance",
      "best friends": "two best friends together",
      "roommates": "two roommates together",
      "mother and daughter": "MILF mother and adult daughter roleplay, older and younger woman, family resemblance",
      "stepmom and stepdaughter": "stepmom and adult stepdaughter roleplay, mature and young",
      "aunt and niece": "hot aunt and adult niece roleplay, mature and young",
      "grandma and granddaughter": "sexy granny and adult granddaughter roleplay, mature GILF and young",
      "milf granny": "sexy MILF granny, mature older woman",
      "mature and young": "mature older woman and young adult, age contrast",
      "teacher and student": "teacher and adult student roleplay",
      "boss and secretary": "boss and secretary roleplay",
      "nurse and patient": "nurse and patient roleplay",
      "coach and athlete": "coach and athlete roleplay",
      "dominant and submissive": "dominant and submissive pairing, dom and sub",
      "wife and mistress": "wife and mistress pairing",
    },
    roleplay: {
      "girl next door": "innocent girl-next-door character",
      "sexy stepmom": "sexy stepmom MILF character, mature seductress",
      "hot aunt": "hot aunt MILF character",
      "sexy granny": "sexy GILF granny character, mature grandmother",
      "milf": "MILF character, mature confident mother figure",
      "cougar": "cougar MILF, older woman seducing younger",
      "sugar mommy": "sugar mommy character, wealthy older seductress",
      "lonely housewife": "lonely bored housewife character, needy",
      "trophy wife": "gold-digger trophy wife character",
      "best friend's mom": "best friend's hot mom character",
      "step-sister": "step-sister character",
      "schoolgirl": "sexy schoolgirl character, innocent naughty",
      "college coed": "college coed character",
      "sorority girl": "sorority girl character",
      "cheerleader": "hot cheerleader character",
      "librarian": "naughty librarian character",
      "teacher": "sexy teacher character",
      "secretary": "sexy secretary character",
      "boss lady": "dominant boss lady character",
      "nurse": "naughty nurse character",
      "doctor": "sexy female doctor character",
      "yoga instructor": "sexy yoga instructor character",
      "personal trainer": "sexy fitness trainer character",
      "maid": "sexy French maid character",
      "waitress": "sexy waitress character",
      "flight attendant": "sexy flight attendant character",
      "dominatrix": "strict dominatrix character",
      "submissive": "obedient submissive character",
      "gothic girl": "gothic goth girl character, dark alternative",
      "e-girl": "e-girl character, alternative internet aesthetic",
      "onlyfans model": "OnlyFans model character",
      "cam girl": "webcam girl character",
      "porn star": "professional pornstar character",
    },
    acts: {
      "posing": "seductively posing for camera",
      "teasing": "teasing camera, slowly revealing, coy",
      "stripping": "mid-strip, undressing sensually",
      "flashing": "flashing pussy or tits at camera",
      "upskirt": "upskirt view, panties visible under skirt",
      "exposed": "fully exposed, nothing hidden",
      "spread eagle": "spread eagle position, legs and arms wide open, everything exposed",
      "spreading pussy": "using fingers to spread pussy lips open, holding lips apart",
      "masturbating": "solo masturbating, one hand between legs, fingers on clit, self-pleasuring",
      "fingering": "fingering own pussy, fingers inside vagina",
      "using dildo": "using a large dildo, pussy penetrated by sex toy",
      "using vibrator": "using a vibrator on clit, buzzing sex toy",
      "using rabbit": "using a rabbit vibrator on pussy and clit",
      "riding toy": "riding a huge dildo, straddling sex toy",
      "oral": "receiving oral sex, being eaten out, mouth on pussy",
      "blowjob": "giving a blowjob, mouth wrapped around cock, sucking eagerly",
      "deepthroat": "deepthroating cock, all the way down throat, gagging drool",
      "throatpie": "throatpie, cum shot deep in throat",
      "titfucking": "titfucking, cock between big breasts, sliding between tits",
      "handjob": "giving a handjob, hand stroking cock",
      "missionary": "having sex in missionary position, on back, legs up, being penetrated",
      "cowgirl": "riding on top cowgirl style, straddling and bouncing on cock",
      "reverse cowgirl": "reverse cowgirl, riding facing away, back arched, ass bouncing",
      "doggy style": "being fucked doggy style from behind, on all fours, hips gripped",
      "prone bone": "prone bone position, face down flat on stomach being fucked from behind",
      "spooning": "spooning sex position, side by side penetration",
      "standing sex": "standing sex position, leg raised, being fucked while standing",
      "against wall": "sex against wall, pinned and fucked against wall",
      "table sex": "having sex on a table, bent over table being fucked",
      "bent over": "bent over being fucked from behind, ass in the air",
      "legs on shoulders": "legs on partner's shoulders, deep penetration",
      "amazon position": "amazon position, riding on top with legs squatting over him",
      "anal": "anal sex, cock deep in tight asshole, being penetrated anally",
      "anal doggy": "anal doggy style, taking cock in ass from behind",
      "anal reverse cowgirl": "anal reverse cowgirl, riding cock in ass",
      "double penetration": "double penetration, one cock in pussy and one in ass simultaneously",
      "DAP": "double anal penetration, two cocks in ass",
      "DVP": "double vaginal penetration, two cocks in pussy",
      "DP": "DP double penetration, cocks in both holes",
      "facesitting": "facesitting, pussy on face, smothering partner",
      "sixty-nine": "sixty-nine position, mutual oral",
      "eating pussy": "eating pussy, tongue in vagina, licking labia",
      "rimming": "rimming asshole, tongue in ass",
      "lesbian": "lesbian scene, two women together",
      "tribbing": "tribbing, scissoring pussy against pussy",
      "scissoring": "scissoring, pussies pressed together, grinding",
      "strap-on": "using a strap-on dildo, wearing harness",
      "creampie": "creampie, cum dripping out of pussy, freshly filled full of cum",
      "cumshot": "cumshot, ropes of cum, ejaculation captured",
      "facial": "facial cumshot, cum on face, semen on cheeks lips and forehead",
      "bukkake": "bukkake scene, multiple cumshots covering face and body",
      "cum on tits": "cum on tits, semen dripping down breasts",
      "cum on ass": "cum on ass, semen dripping down butt cheeks",
      "cum on face": "cum on face, big load on cheeks and lips",
      "swallowing": "swallowing cum, cum in mouth being swallowed",
      "squirting": "squirting orgasm, streams of female ejaculation, pussy squirting fluid",
      "fisting": "fisting, fist inserted in pussy",
      "gaping": "gaping open hole, pussy or ass stretched wide and gaping",
      "stretched": "stretched hole, ring of pleasure",
      "bondage": "in bondage, restrained and tied up",
      "shibari": "elaborate shibari rope bondage, intricate kinbaku ties",
      "tied up": "tied up with rope, wrists and ankles bound",
      "collared and leashed": "wearing collar and leash, held submissively",
      "spanking": "being spanked, red handprints on ass cheeks",
      "gagged": "ball gagged, drool dripping from mouth",
    },
  },

  scene: {
    environment: {
      "studio": "professional photography studio, seamless backdrop",
      "beach": "tropical beach, ocean waves, sand, sunset",
      "forest": "misty forest, tall trees, natural lighting",
      "urban street": "urban city street, night lights, neon signs",
      "rooftop": "high-rise rooftop, city skyline background",
      "bedroom": "luxury bedroom, silk sheets, king bed, romantic",
      "warehouse": "abandoned industrial warehouse, gritty",
      "desert": "vast desert landscape, sand dunes, dramatic sky",
      "neon alley": "neon-lit alley, cyberpunk atmosphere, wet reflective ground",
      "castle": "medieval stone castle interior, torch-lit",
    },
    era: {
      "80s": "1980s retro aesthetic, big hair, neon",
      "90s": "1990s aesthetic, minimalist grunge",
      "vintage": "vintage retro aesthetic, film photography style",
      "futuristic": "futuristic sci-fi aesthetic",
      "medieval": "medieval fantasy aesthetic",
      "victorian": "victorian era aesthetic, corsets and lace",
      "cyberpunk": "cyberpunk neon-noir aesthetic",
    },
  },

  lighting: {
    source: {
      "natural": "natural sunlight, golden warm light",
      "window": "soft window light streaming in",
      "softbox": "professional softbox studio lighting, even soft light",
      "hard key": "hard directional key light, dramatic shadows",
      "neon": "colorful neon lighting, purple pink cyan glow",
      "candle": "warm candlelight, flickering intimate glow",
      "firelight": "warm firelight, flickering orange glow",
      "moonlight": "soft cool moonlight",
    },
    style: {
      "cinematic": "cinematic lighting, film-like quality",
      "chiaroscuro": "dramatic chiaroscuro lighting, high contrast between light and shadow",
      "high-key": "high-key bright even lighting",
      "low-key": "low-key moody dark lighting with selective highlights",
      "golden hour": "golden hour warm sunset lighting",
      "blue hour": "blue hour twilight lighting",
      "hard shadows": "hard defined shadows, dramatic light falloff",
    },
    mood: {
      "dramatic": "dramatic moody atmosphere",
      "soft": "soft romantic atmosphere",
      "moody": "moody dark atmosphere",
      "sensual": "deeply sensual erotic atmosphere",
      "harsh": "harsh unforgiving lighting",
    },
  },

  camera: {
    lens: {
      "24mm": "24mm wide angle lens",
      "35mm": "35mm lens, natural perspective",
      "50mm": "50mm nifty-fifty lens, natural perspective",
      "85mm": "85mm portrait lens, beautiful bokeh",
      "135mm": "135mm telephoto portrait lens, compressed perspective",
      "macro": "macro lens, extreme detail",
    },
    aperture: {
      "f/1.4": "shot at f/1.4, extremely shallow depth of field, creamy bokeh",
      "f/1.8": "shot at f/1.8, shallow depth of field",
      "f/2.8": "shot at f/2.8, moderate depth of field",
    },
  },

  style: {
    render: {
      "photorealistic": "photorealistic, ultra-detailed, hyperrealistic photography",
      "cinematic": "cinematic film-like quality, movie still",
      "analog film": "analog 35mm film photography, film grain, kodak portra",
      "editorial": "editorial fashion photography style, high-end magazine quality",
      "documentary": "documentary photojournalism style, candid",
      "35mm film": "35mm film photograph, grainy analog quality",
    },
    artistic_tone: {
      "moody": "moody dark tonal grading",
      "vibrant": "vibrant saturated colors",
      "desaturated": "desaturated muted color palette",
      "high-contrast": "high contrast, punchy",
      "faded": "faded vintage tone, washed out",
    },
  },
};

export function expandPrompt(section, field, value) {
  if (!value) return "";
  const mapped = PROMPT_MAP?.[section]?.[field]?.[value];
  return mapped || value;
}
