// Prompt expansion map: turns each DNA chip / option into a rich prompt phrase
// suitable for SDXL / Flux / Chroma / Qwen / IPAdapter workflows.
// Structure: PROMPT_MAP[sectionKey][fieldKey][optionValue] = "detailed phrase"
// Anything not mapped falls back to the raw value.

export const PROMPT_MAP = {
  identity: {
    gender: {
      "female": "adult woman, feminine features",
      "male": "adult man, masculine features",
      "non-binary": "androgynous adult, gender-fluid features",
      "androgynous": "androgynous beauty, ambiguous gender presentation",
    },
    ethnicity: {
      "latina": "Latina heritage, expressive eyes, distinctive Latin facial features",
      "mexican": "Mexican heritage, expressive dark eyes, distinctive Mexican facial features",
      "brazilian": "Brazilian heritage, expressive eyes, distinctive Brazilian facial features",
      "colombian": "Colombian heritage, expressive dark eyes, distinctive Colombian facial features",
      "puerto rican": "Puerto Rican heritage, expressive eyes, distinctive Caribbean-Latin facial features",
      "cuban": "Cuban heritage, expressive dark eyes, distinctive Cuban facial features",
      "dominican": "Dominican heritage, expressive eyes, distinctive Caribbean facial features",
      "venezuelan": "Venezuelan heritage, refined Latin facial features",
      "argentinian": "Argentinian heritage, distinctive European-Latin facial features",
      "peruvian": "Peruvian heritage, distinctive Andean and indigenous facial features",
      "east asian": "East Asian heritage, almond-shaped eyes, delicate facial features",
      "japanese": "Japanese heritage, almond-shaped eyes, delicate Japanese facial features",
      "korean": "Korean heritage, almond-shaped eyes, elegant Korean facial features",
      "chinese": "Chinese heritage, almond-shaped eyes, elegant Chinese facial features",
      "vietnamese": "Vietnamese heritage, expressive dark eyes, distinctive Vietnamese facial features",
      "thai": "Thai heritage, distinctive Southeast Asian facial features",
      "filipina": "Filipina heritage, expressive dark eyes, distinctive Filipina facial features",
      "indonesian": "Indonesian heritage, distinctive Indonesian facial features",
      "cambodian": "Cambodian heritage, distinctive Khmer facial features",
      "south asian": "South Asian heritage, expressive dark eyes, distinctive South Asian facial features",
      "indian": "Indian heritage, expressive dark eyes, distinctive Indian facial features",
      "pakistani": "Pakistani heritage, expressive dark eyes, distinctive Pakistani facial features",
      "bangladeshi": "Bangladeshi heritage, expressive dark eyes, distinctive Bengali facial features",
      "sri lankan": "Sri Lankan heritage, expressive dark eyes, distinctive Sri Lankan facial features",
      "black": "Black heritage, distinctive African facial features",
      "african american": "African American heritage, distinctive African-American facial features",
      "ebony": "African heritage, strong elegant facial features",
      "afro-caribbean": "Afro-Caribbean heritage, distinctive Caribbean and African facial features",
      "nigerian": "Nigerian heritage, distinctive West African facial features",
      "ethiopian": "Ethiopian heritage, elegant East African facial features",
      "somali": "Somali heritage, elegant East African facial features, high cheekbones",
      "white": "European heritage, classical European facial features",
      "caucasian": "Caucasian heritage, classical European facial features",
      "european": "European heritage, refined European facial features",
      "british": "British heritage, classic British facial features",
      "french": "French heritage, refined French facial features",
      "german": "German heritage, distinctive Central European facial features",
      "italian": "Italian heritage, expressive eyes, classic Italian facial features",
      "spanish": "Spanish heritage, expressive eyes, classic Iberian facial features",
      "irish": "Irish heritage, distinctive Celtic facial features",
      "russian": "Russian heritage, distinctive Slavic facial features, defined cheekbones",
      "polish": "Polish heritage, distinctive Slavic facial features",
      "nordic": "Nordic heritage, distinctive Northern European facial features",
      "scandinavian": "Scandinavian heritage, distinctive Northern European facial features",
      "swedish": "Swedish heritage, distinctive Scandinavian facial features",
      "norwegian": "Norwegian heritage, distinctive Scandinavian facial features",
      "icelandic": "Icelandic heritage, distinctive Nordic facial features",
      "middle eastern": "Middle Eastern heritage, expressive almond-shaped eyes, distinctive Middle Eastern facial features",
      "arab": "Arab heritage, almond-shaped eyes, distinctive Arab facial features",
      "persian": "Persian heritage, expressive eyes, refined Persian facial features",
      "turkish": "Turkish heritage, expressive eyes, distinctive Anatolian facial features",
      "lebanese": "Lebanese heritage, expressive eyes, distinctive Levantine facial features",
      "egyptian": "Egyptian heritage, expressive almond-shaped eyes, distinctive Egyptian facial features",
      "moroccan": "Moroccan heritage, distinctive North African facial features",
      "israeli": "Israeli heritage, distinctive Levantine facial features",
      "polynesian": "Polynesian heritage, distinctive Polynesian facial features",
      "hawaiian": "Hawaiian heritage, distinctive Native Hawaiian facial features",
      "samoan": "Samoan heritage, distinctive Samoan facial features",
      "maori": "Maori heritage, distinctive Maori facial features",
      "native american": "Native American heritage, distinctive indigenous facial features",
      "indigenous": "Indigenous heritage, distinctive traditional facial features",
      "mixed": "mixed-race heritage, distinctive blended facial features",
      "blasian": "Black and Asian heritage, distinctive blended facial features",
      "afro-latina": "African and Latin heritage, distinctive blended facial features",
      "eurasian": "European and Asian heritage, distinctive blended facial features",
      "mulatto": "mixed African and European heritage, distinctive blended facial features",
      "mestiza": "indigenous and European heritage, distinctive blended facial features",
      "creole": "Creole heritage, distinctive blended facial features",
      "amerasian": "American and Asian heritage, distinctive blended facial features",
      "mediterranean": "Mediterranean heritage, classic Southern European facial features",
      "greek": "Greek heritage, classical Mediterranean facial features",
    },
    archetype: {
      "girl next door": "wholesome girl-next-door charm, natural approachable beauty, warm smile",
      "femme fatale": "seductive femme fatale, dangerous allure, mysterious dark energy, dominant presence",
      "warrior": "fierce warrior woman, battle-ready confident stance, powerful",
      "pirate": "sexy pirate queen, tattered corset, hoop earrings, sword at hip, weathered beauty",
      "cyberpunk": "cyberpunk cyber-goth aesthetic, neon accents, futuristic tech, edgy",
      "goth": "dark gothic aesthetic, black lipstick, pale skin, brooding beauty, alternative style",
      "cottagecore": "soft cottagecore aesthetic, romantic pastoral, flowing dresses, natural",
      "athlete": "athletic fitness-model physique, defined muscles, healthy glow, confident",
      "queen": "regal queenly presence, elegant powerful, refined beauty, commanding",
      "bombshell": "classic Hollywood bombshell, blonde ambition, curvy glamour, red lips",
      "amazonian": "tall statuesque amazonian goddess, powerful strong body, commanding presence",
    },
  },

  physique: {
    body_type: {
      "slim": "slim slender build, delicate frame",
      "athletic": "athletic toned build, defined muscles, fit physique",
      "curvy": "curvy voluptuous figure, generous curves, feminine proportions",
      "voluptuous": "extremely voluptuous body, abundant curves, thick and luscious",
      "plus size": "beautiful plus-size BBW figure, thick voluptuous body, generous curves",
      "hourglass": "perfect hourglass figure, cinched narrow waist, ample bust and hips, dramatic curves",
      "pear": "pear-shaped figure, narrow waist, generous hips and thighs, prominent rear",
      "apple": "apple-shaped figure, fuller midsection, curvy bust",
      "bombshell": "classic bombshell curves, dramatic hourglass, extreme feminine proportions",
      "amazonian": "tall statuesque amazonian body, long powerful limbs",
    },
    bust: {
      "flat": "flat chest, small AA cup, boyish chest",
      "small": "small perky A-cup breasts",
      "medium": "medium B-C cup natural breasts",
      "large": "large heavy D-cup breasts, prominent cleavage",
      "very large": "very large heavy DD-cup breasts, massive cleavage",
      "huge": "huge massive G-cup breasts, enormous cleavage, spilling out, gravity-affected",
      "enormous": "enormous H-cup+ tits, gigantic breasts, dramatic overflowing cleavage",
      "hyper": "hyper-inflated impossibly huge breasts, cartoonishly enormous tits, gravity-defying",
    },
    bust_shape: {
      "natural": "natural sagging teardrop breasts, realistic weight",
      "perky": "perky firm upturned breasts, youthful",
      "round": "perfectly round full breasts, spherical",
      "teardrop": "beautiful teardrop-shaped natural breasts",
      "athletic": "small athletic firm breasts, muscled chest",
      "augmented": "obviously fake augmented breasts, round implants, firm and high",
      "gravity-defying": "impossibly gravity-defying breasts, unnaturally high and firm",
    },
    butt: {
      "flat": "flat pancake ass, small buttocks",
      "small": "small tight ass, petite butt",
      "toned": "toned firm athletic ass, sculpted glutes",
      "round": "round shapely ass, perfectly curved buttocks",
      "bubble": "gorgeous bubble butt, perky round rear, prominent shelf ass",
      "large": "large juicy ass, big round buttocks, prominent rear",
      "very large": "very large jiggly ass, massive round butt",
      "huge": "huge enormous ass, gigantic buttocks, PAWG rear",
      "hyper": "hyper-sized cartoonishly enormous ass, impossibly huge butt, extreme bubble",
    },
    thighs: {
      "slim": "slim slender thighs",
      "toned": "toned athletic thighs, defined muscles",
      "athletic": "athletic muscled thighs, powerful legs",
      "thick": "thick juicy thighs, meaty legs, curvy",
      "very thick": "extremely thick thighs, huge meaty juicy legs, thigh gap gone",
      "massive": "massive tree-trunk thighs, cartoonishly thick legs",
    },
    hips: {
      "narrow": "narrow slim hips",
      "average": "average natural hips",
      "wide": "wide childbearing hips, curvy pelvis",
      "very wide": "extremely wide hips, dramatic hip-to-waist ratio",
      "extreme": "impossibly wide hips, exaggerated pelvis, extreme hourglass",
    },
    waist: {
      "thick": "thick natural waist",
      "average": "average natural waist",
      "slim": "slim narrow waist",
      "cinched": "strongly defined narrow waist, pronounced waist-to-hip ratio",
      "tiny": "impossibly tiny waist, wasp waist",
      "wasp-thin": "extremely narrow wasp waist, dramatic waist-to-hip ratio",
    },
    shoulders: {
      "narrow": "narrow feminine shoulders",
      "broad": "broad shoulders, powerful build",
      "athletic": "athletic sculpted shoulders",
    },
    legs: {
      "short": "short legs",
      "average": "average legs",
      "long": "long shapely legs",
      "endless": "impossibly long endless legs, dramatic leg length",
    },
  },

  face: {
    eye_shape: {
      "almond": "beautiful almond-shaped eyes, elegant eye shape",
      "round": "large round doe eyes, big innocent eyes",
      "hooded": "sexy hooded bedroom eyes, sultry heavy lids",
      "monolid": "elegant monolid Asian eyes",
      "upturned": "cat-like upturned eyes, feline shape",
      "downturned": "soft downturned eyes, puppy-dog gaze",
    },
    eye_color: {
      "deep brown": "deep chocolate brown eyes",
      "hazel": "warm hazel eyes with green flecks",
      "green": "striking emerald green eyes",
      "blue": "piercing crystal blue eyes",
      "grey": "cold steel grey eyes",
      "amber": "unusual amber golden eyes",
      "violet": "rare stunning violet purple eyes",
    },
    jawline: {
      "soft": "soft rounded jawline, gentle feminine face",
      "defined": "defined sculpted jawline",
      "angular": "sharp angular jawline, striking features",
      "square": "strong square jawline",
      "heart-shaped": "delicate heart-shaped face, pointed chin",
    },
    lips: {
      "thin": "thin delicate lips",
      "medium": "medium natural lips",
      "full": "full plump pouty lips, luscious pillowy lips",
      "pouty": "sexy pouty pillowy lips, DSL dick-sucking lips",
      "bow-shaped": "perfect cupid's bow lips, dainty bow shape",
    },
    expression: {
      "neutral": "neutral relaxed expression",
      "smirk": "cocky playful smirk, mischievous half-smile",
      "smile": "warm genuine smile, bright expression",
      "serious": "intense serious expression, focused",
      "sultry": "sultry seductive expression, half-lidded bedroom eyes, parted lips, come-hither gaze",
      "laughing": "genuine laugh, joyful expression",
    },
  },

  hair: {
    style: {
      "straight": "sleek straight hair",
      "wavy": "loose beachy waves, tousled wavy hair",
      "curly": "bouncy defined curls, curly hair",
      "coily": "natural coily hair, defined coils",
      "braids": "intricate braided hair, box braids",
      "updo": "elegant updo hairstyle, hair swept up",
      "ponytail": "sexy high ponytail, hair pulled back",
      "messy": "messy tousled bedhead hair, disheveled",
    },
    length: {
      "pixie": "short pixie cut",
      "short bob": "chic short bob haircut",
      "shoulder": "shoulder-length hair",
      "long": "long flowing hair, cascading down back",
      "waist-length": "extremely long waist-length hair, dramatic length",
    },
    color: {
      "jet black": "jet black raven hair, glossy dark",
      "chestnut": "rich chestnut brown hair with warm highlights",
      "auburn": "auburn hair with red and copper highlights",
      "fiery red": "fiery vibrant red hair, striking crimson",
      "platinum blonde": "icy platinum blonde hair",
      "honey blonde": "warm honey blonde hair with golden highlights",
      "silver": "silver gray hair, striking metallic tone",
      "raven": "glossy raven black hair",
      "ombre": "dramatic ombre hair, dark roots fading to light ends",
    },
  },

  skin: {
    tone: {
      "porcelain": "flawless porcelain pale skin, ivory complexion",
      "fair": "fair light skin",
      "olive": "warm olive Mediterranean skin",
      "tan": "sun-kissed tan skin, golden complexion",
      "bronze": "rich bronze skin, deep tan",
      "dark brown": "rich dark brown skin, deep melanin",
      "ebony": "deep ebony skin, rich chocolate complexion",
    },
    texture: {
      "smooth": "flawless smooth skin, poreless complexion",
      "natural pores": "realistic skin with natural pores and texture, high detail",
      "textured": "highly textured skin with visible pores, freckles, and imperfections",
      "matte": "matte velvety skin, no shine",
      "dewy": "dewy glowing skin, healthy sheen, luminous",
      "oiled": "oiled slick glistening skin, wet shiny body oil",
      "sweat-glistening": "sweat-glistening skin, beads of sweat, moist glow, wet body",
    },
    freckles: {
      "light": "light delicate freckles across nose",
      "scattered": "scattered natural freckles across face and shoulders",
      "heavy": "heavy freckles covering face and body, prominent freckling",
    },
  },

  intimate: {
    pubic_hair: {
      "hairless": "completely hairless smooth bare pussy, shaved bald mound",
      "shaved smooth": "freshly shaved smooth pussy, no pubic hair, silky bare mound",
      "stubble": "light stubble regrowth on pubic mound, prickly short pubes",
      "trimmed": "neatly trimmed short pubic hair, well-groomed bush",
      "landing strip": "tidy vertical landing strip of pubic hair, groomed",
      "natural bush": "natural full untamed pubic hair, unshaved bush",
      "hairy": "hairy unshaved pussy, thick pubic hair covering mound",
      "very hairy": "very hairy dense bush, thick full pubic hair, completely unshaved",
      "wild bush": "wild unkempt overgrown pubic bush, big furry unshaved 70s bush",
      "heart-shaped": "cute heart-shaped landing strip of pubic hair",
    },
    pussy: {
      "closed": "tight closed pussy, small labia tucked in neatly",
      "small labia": "small tight pussy lips, tucked inner labia",
      "prominent labia": "prominent meaty labia, outer lips fully visible and protruding",
      "puffy": "puffy plump swollen pussy mound, thick meaty vulva",
      "innie": "innie pussy, labia neatly tucked inside, cameltoe",
      "outie": "outie pussy, protruding meaty labia, hanging inner lips, full prominent vulva",
      "meaty": "meaty thick labia, prominent full vulva, engorged lips",
      "tight": "very tight small pussy, delicate opening",
      "spread": "spread open pussy, exposed labia, vaginal opening visible, everything on display",
      "wet": "wet dripping pussy, glistening arousal fluids, moist labia, aroused and dripping",
    },
    clit: {
      "subtle": "subtle hidden clit under hood",
      "prominent": "prominent engorged aroused clit, visible clitoris",
      "large": "large protruding clit, big engorged clitoris, prominent nub",
      "pierced": "clit hood piercing, jeweled clitoris piercing",
    },
    asshole: {
      "tight": "tight small puckered asshole",
      "visible": "visible tight asshole, exposed anus between cheeks",
      "puckered": "puckered tight pink asshole",
      "trimmed": "clean trimmed asshole, no hair around anus",
      "hairy": "hairy asshole, dense pubic hair around anus, unshaven",
      "bleached": "bleached pink clean asshole, perfectly light and hairless",
      "pierced": "pierced perineum, jeweled anus piercing",
      "spread": "spread wide open asshole, gaping anus, held open",
    },
    nipples: {
      "soft": "soft relaxed nipples",
      "erect": "hard erect stiff nipples, pointing and aroused, poking out",
      "inverted": "inverted shy nipples",
      "small": "small delicate nipples",
      "large": "very large protruding thick nipples, prominent tips",
      "puffy": "puffy dome nipples, plump swollen nipple areolas",
      "pierced": "nipple barbell piercings, jeweled nipple rings, both pierced",
    },
    areolas: {
      "small pale": "small pale pink areolas",
      "medium pink": "medium rosy pink areolas",
      "large brown": "large wide brown areolas, prominent dark areolas",
      "very large dark": "very large dark chocolate brown areolas, huge dinner-plate areolas covering breast",
      "puffy dome": "puffy dome-shaped swollen areolas, plump raised mounds",
    },
    body_hair: {
      "light peach fuzz": "light peach fuzz body hair, natural fine hair",
      "moderate": "moderate natural body hair, arms and legs unshaved",
      "heavy": "heavy body hair, hirsute unshaved arms, legs, and stomach",
      "natural": "natural realistic body hair, unshaved",
      "unshaven armpits": "hairy unshaven armpits, thick underarm hair visible",
    },
    piercings: {
      "nipple": "nipple barbell piercings, jeweled nipple rings",
      "navel": "belly button navel piercing, jeweled",
      "nose": "nose stud piercing",
      "septum": "septum ring piercing",
      "tongue": "tongue barbell piercing",
      "clit hood": "clit hood piercing, jeweled hood ring",
      "labia": "labia piercings, jeweled outer lips",
      "multi": "multiple body piercings, nipples, navel, clit hood, all jeweled",
    },
    cum_state: {
      "cum on face": "cum splattered on face, fresh load across cheeks and lips",
      "cum in mouth open display": "mouth open showing pooled cum on tongue",
      "cum in mouth held": "cum held in mouth, cheeks full",
      "cum on lips": "cum smeared across lips",
      "cum on eyelashes": "cum drops on eyelashes and eyebrows",
      "cum in hair": "cum in hair, sticky strands",
      "cum on tits": "cum ropes dripping down breasts and cleavage",
      "cum on ass": "cum sliding down ass cheeks",
      "cum on stomach": "cum pooled on stomach and belly button",
      "cum on thighs": "cum running down inner thighs",
      "cum-covered whole body": "entire body drenched in cum, dripping",
      "cum drenched": "drenched in cum, glossy sticky finish",
      "fresh creampie": "fresh creampie, pussy full of cum",
      "dripping creampie": "creampie dripping out of pussy, cum leaking down thighs",
      "gaping creampie": "gaping pussy with cum pouring out, stretched hole full of cum",
      "anal creampie": "anal creampie, cum leaking from asshole",
      "ass-to-mouth": "ass-to-mouth, cock or fingers going from ass to lips",
      "pooled cum": "cum pooled in mouth or on skin, glossy puddle",
      "snowballing": "snowballing cum from mouth to mouth",
      "cum swap kiss": "cum-sharing kiss, mouths open swapping cum",
      "cum drool": "cum drooling from mouth, dripping off chin",
      "cum gargle": "gargling cum, throat full of semen",
      "swallowing cum": "swallowing cum, throat visibly gulping",
    },
    saliva: {
      "glossy wet lips": "glossy saliva-slicked wet lips",
      "spit strand": "thin strand of spit between lips",
      "drool from mouth": "drool spilling from open mouth",
      "drool from chin": "spit dripping off chin",
      "spit trail chin to tits": "spit trail from chin down to cleavage",
      "spit-covered cock": "sloppy spit-covered cock, drool everywhere",
      "spit shine on lips": "spit-shined pillowy lips",
      "sloppy spit": "sloppy messy spit-covered everything",
    },
    squirt: {
      "light squirt": "light squirt, small stream from pussy",
      "gushing squirt": "gushing female ejaculation, thick stream squirting from pussy",
      "arcing stream": "arcing squirt stream, jet of ejaculate",
      "mid-squirt": "captured mid-squirt, pussy actively ejaculating",
      "post-squirt puddle": "puddle after squirting, wet aftermath on sheets",
      "squirting on face": "squirting directly on partner's face",
    },
    lactation: {
      "lactating": "lactating breasts, milk leaking from nipples",
      "milk drip": "milk dripping slowly from erect nipples",
      "milk spray": "spraying jets of milk from nipples",
      "breastfeeding": "breastfeeding, nipple in mouth, milk flowing",
      "cow-milked": "being milked like a cow, machine or hands drawing milk from swollen breasts",
    },
    sweat: {
      "dewy": "dewy sweaty glow across skin",
      "glistening": "glistening sweat across body, healthy sheen",
      "sweat-drenched": "sweat-drenched body, dripping with exertion",
      "sweat on brow": "beads of sweat on brow and temples",
      "sweat between tits": "sweat running down cleavage between breasts",
      "wet sheen everywhere": "wet-sheen body, glossy sweat covering every inch",
    },
    lube: {
      "glossy": "glossy lube-slicked skin",
      "dripping lube": "dripping with lube, slick and shiny",
      "oiled up": "oiled up body, baby oil slick",
      "baby oil sheen": "baby-oil sheen across skin, greased and gleaming",
    },
    tears: {
      "single tear": "single glistening tear rolling down cheek",
      "mascara tears": "smeared mascara running down cheeks in black streaks",
      "ugly cry": "full ugly-cry face, tears and snot",
      "tear-streaked face": "tear-streaked face, wet cheeks",
    },
  },

  feet: {
    sole_presentation: {
      "soles up": "soles up toward the camera, both feet presented",
      "soles together": "soles pressed together, feet arched inward",
      "sole showcase": "sole showcased, foot flat toward the viewer",
      "sole toward camera": "single sole pointed straight at camera",
      "one sole raised": "one sole raised, other foot planted",
      "wrinkled soles": "detailed wrinkled soles, natural foot lines",
      "smooth soles": "smooth pristine soles, unmarked skin",
      "oiled soles": "oiled glistening soles, shiny slick feet",
      "dirty soles": "dirty soles, dust and grime on feet",
      "muddy soles": "muddy soles caked in wet earth",
      "freshly washed": "freshly washed clean feet, pink and pampered",
    },
    toes: {
      "toe curl": "curled toes, tension across the foot",
      "toe spread": "toes spread wide apart",
      "toe point": "pointed toes, extended arch",
      "toe suck": "sucking on toes, big toe in mouth",
      "toe ring": "silver toe ring on second toe",
      "toe scrunch": "scrunched toes, gripping motion",
      "big toe out": "big toe pushed out, prominent",
      "toes in mouth": "toes fully in mouth, sucked",
    },
    arch: {
      "high arch": "beautiful high arch, dramatic foot curve",
      "medium arch": "medium natural arch",
      "flat arch": "flat foot, low arch",
      "defined arch": "defined muscular arch",
      "banana arch": "extreme banana arch, curved sole",
    },
    pedicure: {
      "painted red": "glossy red-painted toenails",
      "painted black": "glossy black-painted toenails",
      "painted french": "french-manicure pedicure, white tips",
      "painted pink": "soft pink-painted toenails",
      "chipped polish": "chipped worn nail polish",
      "long nails": "long shaped toenails",
      "sharp claws": "sharp filed talon toenails",
      "glitter polish": "sparkling glitter polish on toes",
      "natural nails": "clean natural toenails",
    },
    foot_size: {
      "petite": "petite delicate feet",
      "large": "large feet, size queen",
      "size queen": "very large feet, dominant size-queen soles",
    },
    foot_state: {
      "bare": "bare naked feet",
      "sweaty": "sweaty glistening feet",
      "oiled": "oiled shiny feet",
      "dirty": "dirty grimy feet",
      "muddy": "muddy feet caked in wet earth",
      "freshly washed": "freshly washed clean feet",
      "in nylons": "feet in sheer nylons",
      "in socks": "feet in cotton socks",
      "stinky": "sweaty stinky feet, well-worn",
      "cum on feet": "cum splattered on feet and toes",
      "cum on soles": "cum dripping down soles",
    },
    hosiery: {
      "sheer stockings": "sheer nude stockings encasing feet",
      "toeless stockings": "toeless sheer stockings, bare toes",
      "footed stockings": "footed sheer stockings covering entire foot",
      "pantyhose": "sheer pantyhose",
      "ripped pantyhose": "ripped torn pantyhose, holes exposing skin",
      "fishnet stockings": "black fishnet stockings, patterned mesh",
      "toeless fishnets": "toeless fishnet stockings, bare toes",
      "ripped fishnets": "torn ripped fishnet stockings",
      "ankle socks": "cute white ankle socks",
      "gym socks": "sweaty white gym socks",
      "knee-high socks": "knee-high socks",
      "thigh-high socks": "thigh-high socks, over the knee",
      "over-the-knee socks": "over-the-knee socks",
      "dirty socks": "dirty worn socks",
      "sweaty socks": "sweaty warm socks",
    },
    foot_act: {
      "foot showcase": "presenting feet to camera as the subject",
      "foot posing": "feet posed dramatically",
      "foot tease": "teasing with feet, sensual foot play",
      "arched foot": "dramatically arched foot",
      "toe suck self": "sucking own toes, foot to mouth",
      "foot worship": "foot worship, feet being adored",
      "sole licking": "tongue licking soles",
      "toe sucking": "toes being sucked in partner's mouth",
      "foot kissing": "feet being kissed devotionally",
      "foot massage": "feet being massaged",
      "footjob": "giving a footjob, cock between soles",
      "double footjob": "double footjob, both feet stroking cock",
      "foot on cock": "sole pressed against cock",
      "foot in mouth POV": "POV foot in mouth, toes on tongue",
      "foot on face": "foot placed dominantly on partner's face",
      "foot smothering": "foot smothering, sole pressed to face",
      "trampling": "trampling under bare feet",
      "standing on someone": "standing on partner, foot domination",
      "foot gag": "foot in mouth as gag",
      "cum between toes": "cum pooled between toes",
    },
    framing: {
      "waist-down": "waist-down framing, focus on lower body and feet",
      "knees-down": "knees-down framing, feet prominent",
      "feet close-up": "extreme close-up of feet",
      "sole close-up": "extreme close-up of sole",
      "POV under foot": "POV shot from beneath a foot looking up",
      "low angle sole": "low angle looking up at sole",
    },
  },

  kink: {
    restraint: {
      "rope shibari": "elaborate Japanese shibari kinbaku rope bondage, red rope wrapped around body",
      "hemp bondage": "hemp rope bondage, natural rope ties",
      "leather cuffs": "black leather wrist and ankle cuffs",
      "metal handcuffs": "steel handcuffs locking wrists",
      "straitjacket": "white straitjacket, arms bound across chest",
      "spreader bar": "metal spreader bar between ankles, legs forced apart",
      "hogtie": "hogtied, wrists and ankles bound together behind back",
      "suspension": "rope suspension bondage, suspended in the air",
      "chair-tied": "tied to a chair, arms and legs bound",
      "tied to bed": "tied spread-eagle to a bed frame",
      "wrists overhead": "wrists bound above head",
      "ankle cuffs": "ankle cuffs and chains",
      "thigh cuffs": "thigh cuffs strapped tight",
      "chastity cage": "chastity cage locked in place",
      "chastity belt": "steel chastity belt",
      "collar and leash": "leather collar with attached leash",
      "arms behind back": "arms bound tight behind back",
      "frogtie": "frogtied, legs folded and tied to thighs",
    },
    gag: {
      "ball gag": "red ball gag strapped in mouth, drool escaping",
      "ring gag": "metal ring gag holding mouth open, tongue visible",
      "bit gag": "leather bit gag",
      "cleave gag": "cloth cleave gag pulled between teeth",
      "tape gag": "duct tape over mouth",
      "panty gag": "panties stuffed in mouth as gag",
      "drool bib": "wet drool bib beneath gagged mouth",
      "dildo gag": "dildo strap gag in mouth",
      "muzzle": "leather muzzle over lower face",
      "spider gag": "metal spider gag holding jaws wide open",
    },
    marks: {
      "spanking": "being spanked, mid-strike",
      "red handprint": "bright red handprint marks on ass cheeks",
      "paddled": "paddled ass, welts from wooden paddle",
      "caned": "caned skin, thin welt lines from cane",
      "whipped": "whipped body, welts from single-tail whip",
      "cropped": "cropped skin, riding-crop welts",
      "welts": "raised red welts across skin",
      "bruises": "bruised marks, purple and yellow discoloration",
      "rope marks": "rope indentation marks on skin after bondage",
      "scratched": "long red scratch marks across skin",
      "bite marks": "clear bite marks on shoulders and neck",
      "hickeys": "purple hickey marks on neck and chest",
      "belt marks": "belt-strap welts across ass and thighs",
    },
    sensation: {
      "wax play": "hot candle wax dripping onto skin",
      "hot wax on tits": "hot wax poured onto breasts and nipples",
      "ice play": "ice cube gliding across nipples, wet trail",
      "electro pads": "electro-stim pads attached to skin",
      "needle play": "fine needles pierced through skin, play piercing",
      "clothespins": "row of wooden clothespins clipped along skin",
      "clover clamps": "clover-style tit clamps with connecting chain",
      "nipple clamps": "metal nipple clamps biting into nipples",
      "clamps with weights": "nipple clamps with hanging weights pulling down",
      "tit slaps": "mid-slap on breasts, hand impact on tit",
      "nipple twist": "nipples being twisted between fingers",
      "hair pulling": "hair yanked back hard by fistful",
    },
    humiliation: {
      "collared pet": "collared like a pet, being led",
      "puppy hood": "puppy hood mask, ears and snout",
      "kitten ears and tail plug": "kitten ears headband and tail buttplug",
      "ponygirl gear": "full ponygirl gear, tail plug, bit gag, hoof boots",
      "on all fours pet": "crawling on all fours like an animal",
      "leash walk": "being walked on leash, hands and knees",
      "food bowl": "eating from a food bowl on floor",
      "degradation stare": "eye contact begging to be degraded further",
      "spit on face": "spit dripping down face",
      "face-fucked": "face-fucked, throat used roughly",
      "used": "used up, exhausted fuck-toy",
      "wrecked": "wrecked and destroyed, ruined by pleasure",
      "spit-drenched": "drenched in spit, sloppy wet face",
      "ahegao expression": "ahegao face, tongue out, eyes rolled back, cock-drunk",
      "mind-break": "mind-broken expression, blank cock-drunk gaze",
      "tongue-out": "tongue lolled out of mouth",
      "rolled-back eyes": "eyes rolled back into head",
      "drooling": "drool spilling from mouth",
      "mascara tears": "black mascara tears running down cheeks",
      "slut-face": "slut-face expression, fucked stupid",
    },
    orgasm_control: {
      "edged": "edged and denied, right at the brink",
      "denied": "orgasm denied, trembling with need",
      "ruined orgasm": "ruined orgasm, stopped mid-cum",
      "forced orgasm": "forced orgasm, made to cum against will",
      "hitachi torture": "hitachi wand pressed against clit, orgasm torture",
      "overstimulation": "post-orgasm overstimulation torture",
      "post-orgasm torture": "continued play after climax, oversensitive torture",
      "chastity release": "chastity finally released, first orgasm in weeks",
      "milked dry": "milked dry, no cum left",
      "back-to-back orgasms": "back-to-back forced orgasms, no rest",
    },
    power_dynamic: {
      "dominant": "dominant top, in complete control",
      "submissive": "submissive bottom, obedient and yielding",
      "brat": "bratty sub, pushing back and being punished",
      "switch": "switch dynamic, trading control",
      "master and slave": "master and slave dynamic, absolute ownership",
      "mistress and slave": "mistress and slave dynamic, female domination",
      "owner and pet": "owner and pet dynamic",
      "princess and daddy dom": "princess and daddy dom dynamic",
      "mommy dom and boy": "mommy dom and submissive boy dynamic",
      "slut in training": "slut being trained, obedience under instruction",
      "goddess and worshipper": "goddess and worshipping devotee dynamic",
    },
    group_kink: {
      "gangbang": "gangbang scene, one subject with multiple partners",
      "train": "running a train, taken one after another",
      "double penetration": "double penetration, both holes filled",
      "triple penetration": "triple penetration, all holes filled",
      "air-tight": "air-tight, every hole plugged",
      "bukkake": "bukkake, painted in cum by multiple partners",
      "blowbang": "blowbang, sucking many cocks",
      "spitroast": "spitroast, penetrated from both ends",
      "eiffel tower": "eiffel tower position, two partners meeting overhead",
    },
  },

  watersports: {
    source: {
      "self": "self-pissing, pissing on own body",
      "partner": "partner pissing on subject",
      "mutual": "mutual pissing, both parties",
      "group": "group pissing scene, multiple streams",
      "unknown POV": "anonymous POV pisser",
    },
    direction: {
      "in mouth": "piss stream directly into open mouth",
      "on face": "piss on face, stream splashing across cheeks",
      "on tits": "piss on breasts and cleavage",
      "on ass": "piss on ass cheeks",
      "on feet": "piss on feet, wet toes",
      "on floor": "piss puddling on the floor",
      "on another person": "pissing onto another person",
      "inside pussy": "piss inside pussy, held in",
      "inside ass": "piss enema, held in the ass",
      "held in": "holding piss inside, retention",
      "forced held-in": "forced to hold piss, no release allowed",
    },
    stream: {
      "trickle": "faint trickle of piss",
      "steady stream": "steady thick stream of piss",
      "gush": "gushing torrent of piss",
      "spray": "sprayed splattering piss",
      "arc": "arcing yellow stream of piss",
      "pooling": "pooling puddle of piss",
      "explosive": "explosive release, piss going everywhere",
    },
    container: {
      "toilet": "sitting on the toilet",
      "tub": "in the bathtub",
      "shower": "in the shower, water and piss mixing",
      "outdoors": "outdoors in nature",
      "in panties": "pissing in panties, fabric soaked",
      "in jeans": "pissing in jeans, wet stain spreading",
      "on bed": "on the bed, sheets soaked",
      "into glass": "pissing into a drinking glass",
      "into cup": "pissing into a cup",
      "through funnel": "pissing through a funnel into partner's mouth",
      "public": "in public, humiliating exposure",
    },
    wetness: {
      "damp": "damp underwear, small wet spot",
      "soaked panties": "panties completely soaked through",
      "soaked jeans": "jeans dark with piss stain",
      "dripping thighs": "piss dripping down inner thighs",
      "puddle at feet": "puddle of piss forming at feet",
      "running down legs": "piss running down both legs",
      "wet floor": "wet floor covered in piss",
    },
    desperation: {
      "calm": "calm controlled release",
      "needy": "needy to piss, squirming",
      "holding it": "holding piss, thighs pressed together",
      "about to burst": "about to burst, desperate expression",
      "losing control": "losing control mid-hold, first spurts escaping",
      "humiliated": "humiliated by inability to hold it",
    },
    aftermath: {
      "glistening skin": "glistening piss-slicked skin",
      "wet hair": "hair soaked with piss",
      "wet clothes": "clothes drenched with piss",
      "matted fur": "matted wet pubic hair after being pissed on",
      "standing in puddle": "standing in a puddle of piss",
      "smeared mascara": "smeared mascara running down cheeks",
      "post-piss glow": "flushed post-piss satisfaction glow",
    },
  },

  wardrobe: {
    outfit_preset: {
      "nude": "completely nude, fully naked, bare exposed body, no clothing",
      "topless": "topless, bare breasts fully exposed, no top on",
      "bottomless": "bottomless, wearing only a top, no pants or panties, pussy exposed",
      "boudoir lingerie": "elegant boudoir lingerie set, lace and satin, intricate details",
      "sheer negligee": "sheer see-through negligee, transparent lingerie revealing everything underneath",
      "silk robe open": "silk robe hanging open loosely, nothing underneath, breasts and body visible",
      "wet t-shirt": "soaked wet t-shirt clinging to nipples, transparent when wet, no bra",
      "bikini": "sexy bikini set, string bikini top and bottom",
      "micro bikini": "extreme micro bikini, tiny strings barely covering, most of body exposed",
      "string bikini": "string bikini, thin ties, minimal coverage",
      "sexy schoolgirl": "sexy schoolgirl outfit, plaid mini skirt, white blouse tied at midriff, knee-high socks, mary jane shoes",
      "naughty nurse": "sexy nurse costume, unbuttoned white uniform showing cleavage, red cross, white stockings and heels",
      "french maid": "sexy french maid costume, black and white ruffled dress, mini skirt, fishnet stockings, apron, feather duster",
      "playboy bunny": "Playboy bunny costume, satin corset bodice, bunny ears, fluffy cotton tail, fishnet stockings, black stilettos",
      "showgirl": "Las Vegas showgirl costume, sequined bodysuit, huge feathered headdress, feather fans, high heels",
      "pole dancer": "sexy pole dancer outfit, tiny sequined bikini, stripper heels, oiled body",
      "gogo dancer": "gogo dancer outfit, metallic mini dress, go-go boots",
      "stripper": "stripper outfit, thigh-high stripper heels, tiny thong, tasseled pasties",
      "cheerleader": "sexy cheerleader uniform, tiny pleated skirt, cropped top, sneakers, pom-poms",
      "dominatrix": "dominatrix in leather, tight leather corset, whip in hand, thigh-high leather boots, latex gloves",
      "leather mistress": "leather mistress outfit, studded leather bodysuit, collar and cuffs, riding crop",
      "latex catsuit": "shiny black latex catsuit, skin-tight second-skin latex bodysuit, glossy zipper up front",
      "kinky harness": "black leather harness across body, strappy fetish gear",
      "shibari rope": "intricate Japanese shibari rope bondage, red rope wrapped around body, kinbaku ties, breasts squeezed by rope",
      "fetish gimp": "fetish gimp suit, leather hood, zipper mouth, full body latex",
      "secretary unbuttoned": "sexy secretary outfit, tight pencil skirt, blouse unbuttoned showing cleavage, glasses, hair in a bun",
      "librarian undone": "naughty librarian outfit, cardigan falling off shoulder, glasses on tip of nose, tight skirt, hair coming undone",
      "biker chick": "biker chick outfit, leather jacket, tiny denim shorts, ripped fishnets, heavy boots",
      "cowgirl chaps": "sexy cowgirl outfit, leather chaps, denim shorts, cowboy boots, plaid shirt tied at midriff, hat",
      "cop uniform undone": "sexy cop outfit unbuttoned, tight blue uniform shirt open, mini skirt, handcuffs, black stockings",
      "flight attendant undone": "sexy flight attendant outfit undone, tight blazer open, mini skirt, stockings, heels",
      "cocktail dress": "elegant tight cocktail dress, plunging neckline, form-fitting",
      "evening gown slit": "glamorous evening gown with high thigh slit, formal red carpet dress",
      "backless red carpet": "backless red carpet gown, plunging back, full-length dress",
      "club outfit": "sexy nightclub outfit, tiny minidress, stiletto heels",
      "yoga wear": "form-fitting yoga wear, sports bra and yoga pants, athletic",
      "gym set": "matching gym set, sports bra and biker shorts, sweaty workout",
      "sports bra and shorts": "tight sports bra and tiny running shorts, athletic",
      "cheerleader off-duty": "off-duty cheerleader, cropped hoodie, tiny booty shorts, sneakers",
      "streetwear": "trendy streetwear, oversized hoodie, tight jeans, sneakers",
      "casual home": "casual at-home outfit, oversized tee, no bra",
      "just a shirt": "wearing only a large button-down shirt, buttons undone, one shoulder off, nothing underneath",
      "boyfriend's shirt": "wearing only an oversized men's dress shirt, buttons open showing cleavage and panties",
      "just panties": "wearing only tiny panties, otherwise fully nude, topless with panties",
    },
    top: {
      "none": "no top, bare chest, topless",
      "sheer top": "sheer see-through top, transparent fabric showing nipples underneath",
      "mesh top": "black mesh see-through top, fishnet fabric",
      "lace bralette": "delicate lace bralette, semi-sheer",
      "bikini top": "string bikini top",
      "corset": "tight-laced corset pushing up breasts, cinched",
      "bustier": "sexy bustier pushing up cleavage",
      "crop top": "tiny crop top exposing midriff",
      "backless top": "backless top exposing full back",
      "keyhole top": "keyhole cutout top showing cleavage",
      "halter": "halter top, tied behind neck",
      "tube top": "tight tube top, strapless",
      "strapless": "strapless top",
      "wet t-shirt": "wet see-through t-shirt clinging to erect nipples",
      "unbuttoned blouse": "blouse completely unbuttoned, hanging open exposing bra and cleavage",
      "ripped shirt": "torn ripped shirt exposing breasts",
      "nipple pasties": "only tiny nipple pasties covering nipples, otherwise topless",
      "leather harness": "black leather harness across chest, straps between breasts",
      "cage bra": "cage-style strappy leather bra, decorative straps",
      "chainmail top": "chainmail metal top, silver mesh armor",
    },
    bottom: {
      "none": "no bottoms, bottomless, pussy exposed",
      "micro-mini skirt": "extreme micro-mini skirt barely covering, upskirt visible",
      "pencil skirt": "tight pencil skirt hugging hips and thighs",
      "leather skirt": "tight black leather mini skirt",
      "school skirt": "pleated plaid school skirt",
      "denim shorts": "tiny cutoff denim shorts",
      "hot pants": "tiny hot pants, spandex",
      "booty shorts": "tiny booty shorts riding up, ass cheeks peeking out",
      "yoga pants": "form-fitting yoga pants, hugging every curve",
      "latex leggings": "shiny black latex leggings, second-skin",
      "wet look pants": "shiny wet-look black pants",
      "cutoff jeans": "cutoff denim jean shorts, frayed hem",
      "chaps": "leather chaps, ass and pussy exposed",
      "fishnet stockings": "black fishnet stockings, sexy legwear",
      "garter belt": "black garter belt holding up stockings",
      "thigh-high stockings": "thigh-high stockings with lace tops",
    },
    underwear: {
      "none": "no panties, bottomless underneath",
      "thong": "tiny string thong, T-back",
      "g-string": "g-string barely-there panties",
      "lace panties": "delicate lace panties",
      "sheer panties": "sheer see-through panties revealing everything",
      "crotchless": "crotchless panties, pussy exposed while wearing",
      "microkini": "extreme microkini panties, tiny strings",
      "boy shorts": "cheeky boy short panties",
      "high-waist briefs": "high-waisted retro briefs",
      "teddy": "sexy lingerie teddy bodysuit",
      "babydoll": "sheer babydoll lingerie, flowing sheer top",
      "chemise": "silk chemise slip lingerie",
      "bodysuit": "tight lingerie bodysuit",
      "mesh bodysuit": "sheer mesh bodysuit revealing everything underneath",
      "corset with garters": "corset with attached garter straps and stockings",
      "harness lingerie": "strappy harness lingerie with garter belt",
      "leather harness": "black leather body harness",
      "bikini set": "matching bikini set",
    },
    footwear: {
      "barefoot": "barefoot, bare feet",
      "stiletto heels": "tall stiletto heels, pointed toe",
      "stripper heels": "extreme clear stripper heels, 8-inch platforms",
      "thigh-high boots": "black thigh-high leather boots, stiletto heels",
      "over-the-knee boots": "over-the-knee black boots",
      "ankle boots": "ankle boots, block heel",
      "combat boots": "chunky combat boots",
      "sneakers": "trendy white sneakers",
      "platform heels": "tall chunky platform heels",
      "sandals": "strappy sandals",
      "kitten heels": "low kitten heels",
      "cowgirl boots": "brown cowgirl boots",
    },
    accessories: {
      "choker": "sexy black choker necklace",
      "leather collar": "leather collar with D-ring",
      "leash": "leather collar and leash, held submissively",
      "handcuffs": "metal handcuffs, wrists bound",
      "gloves": "elbow-length gloves",
      "opera gloves": "long black opera gloves",
      "fishnet gloves": "fishnet gloves",
      "garters": "garter belt with straps down thighs",
      "stockings": "sheer thigh-high stockings",
      "veil": "sheer veil over face",
      "cat ears": "cute cat ears headband",
      "bunny ears": "playboy bunny ears headband",
      "devil horns": "sexy red devil horns",
      "angel wings": "white feather angel wings",
      "sunglasses": "designer sunglasses",
      "jewelry": "sparkling diamond jewelry",
      "body chain": "gold body chain draped across torso",
      "belly chain": "gold belly chain around waist",
    },
    material: {
      "latex": "shiny wet-look latex fabric, second-skin glossy black",
      "PVC": "shiny PVC vinyl fabric, glossy",
      "wet look": "shiny wet-look glossy fabric",
      "sheer mesh": "transparent sheer mesh fabric revealing skin underneath",
      "fishnet": "black fishnet mesh fabric",
      "chainmail": "silver metallic chainmail fabric",
      "leather": "black leather, glossy grain",
      "silk": "smooth silk fabric, luxurious sheen",
      "satin": "shiny satin fabric",
      "lace": "delicate intricate lace",
      "velvet": "plush velvet fabric",
    },
    state: {
      "one strap down": "one shoulder strap slipped down, off shoulder",
      "top pulled down": "top pulled down exposing breasts, nipples out",
      "shirt open": "shirt fully open, hanging loose exposing body",
      "unbuttoned": "buttons undone, top hanging open",
      "unzipped": "zipper down, opening exposing skin underneath",
      "panties pulled aside": "panties pulled to the side exposing pussy while still worn",
      "riding up": "skirt riding up thighs, panties visible",
      "coming off": "clothes coming off mid-strip, half-removed",
      "ripped": "clothes torn ripped, exposing skin through tears",
      "disheveled": "clothes disheveled, messy, post-sex look",
    },
  },

  pose: {
    action: {
      "standing": "standing upright, natural stance",
      "standing hip out": "standing with hip cocked out to the side, weight on one leg",
      "standing hands on hips": "standing with hands on hips, confident power pose",
      "standing arms up": "standing with arms raised overhead, stretching",
      "standing back arched": "standing with back arched dramatically, chest pushed forward, ass out",
      "standing legs apart": "standing with legs spread wide apart",
      "standing splits": "doing a standing splits, one leg raised high overhead",
      "walking": "walking toward camera, mid-stride",
      "leaning wall": "leaning back against a wall, hip cocked out",
      "leaning forward": "leaning forward toward camera, breasts hanging down and forward",
      "bending over": "bending over from waist, ass raised high, pussy peeking out",
      "sitting legs crossed": "sitting elegantly with legs crossed",
      "sitting legs open": "sitting with legs spread wide open, pussy exposed",
      "sitting reverse chair": "straddling a chair backwards, arms resting on back",
      "sitting on edge": "sitting on the edge, legs dangling",
      "kneeling upright": "kneeling upright on both knees, thighs together",
      "kneeling back arched": "kneeling with back arched dramatically, chest thrust forward, ass raised",
      "kneeling hands floor": "on hands and knees, kneeling with hands on the floor, ass presented",
      "lying back": "lying flat on back, relaxed",
      "lying side": "lying on side, curves accentuated, hip out",
      "lying stomach": "lying on stomach, ass raised, feet kicked up",
      "lying legs spread": "lying on back with legs spread wide open, pussy fully exposed",
      "lying legs up": "lying with legs raised straight up in the air",
      "on back legs up": "on back with legs pulled up to shoulders, ankles by head, pussy fully exposed and vulnerable",
      "all fours": "on all fours on hands and knees, presenting ass",
      "doggy arched": "on all fours with back arched dramatically, ass raised high, pushed out and presenting, ready for doggy style",
      "doggy low": "chest down ass up, face-down doggy position, ass raised high",
      "squatting": "squatting deeply, thighs open",
      "squatting spread": "squatting with legs spread wide, pussy fully exposed and open",
      "squatting deep": "deep asian squat, ass low to ground",
      "over shoulder look": "back to camera looking seductively over shoulder, ass front and center",
      "arched on knees": "kneeling with back arched dramatically, ass raised, chest low, presenting",
      "hands on knees": "bent forward with hands on knees, cleavage exposed",
      "hair flip": "hair flip mid-motion, dynamic movement",
      "dancing": "sensual dancing, mid-movement, hips shaking",
      "reverse view": "back to camera, rear view, ass and back visible",
    },
    angle: {
      "front": "front-facing view, straight on",
      "3/4": "three-quarter angle view",
      "profile": "side profile view",
      "back": "rear view from behind",
      "over-shoulder": "over-the-shoulder view, looking back at camera",
      "from above": "high angle shot from above, looking down",
      "from below": "low angle shot from below, looking up, dramatic perspective",
      "pov": "point of view shot, first person POV",
    },
    distance: {
      "close-up": "extreme close-up shot, tight framing",
      "portrait": "portrait framing, head and shoulders",
      "waist-up": "waist-up framing, upper body",
      "full body": "full body shot, head to feet visible",
      "wide shot": "wide environmental shot, full scene",
      "detail shot": "extreme detail macro shot",
    },
    focus: {
      "face": "camera focused on face, sharp facial focus",
      "body": "focused on the body, showcasing curves",
      "breasts": "camera zoomed on breasts, cleavage focus, tits front and center",
      "butt": "camera focused on ass, rear-view booty focus",
      "hips": "focused on hips and waist",
      "legs": "focused on long legs",
      "feet": "focused on feet",
      "hands": "focused on hands",
    },
    hands: {
      "at sides": "arms relaxed at sides",
      "on hips": "hands on hips",
      "in hair": "hands running through hair, seductive",
      "touching body": "hands seductively touching own body, self-caressing",
      "on breasts": "hands cupping own breasts, groping, squeezing",
      "between legs": "hand between legs, touching pussy, masturbating",
      "gripping something": "gripping something tightly",
      "over head": "arms raised overhead",
      "behind back": "hands clasped behind back, submissive",
      "behind head": "hands behind head, elbows out",
    },
    body_language: {
      "sultry": "sultry seductive body language, dripping sex appeal",
      "confident": "confident powerful stance, dominant energy",
      "playful": "playful flirtatious energy, teasing",
      "sensual": "deeply sensual, oozing sexuality",
      "come-hither": "come-hither expression, beckoning gaze",
      "dominant": "dominant powerful energy, in charge",
      "submissive": "submissive vulnerable energy, obedient posture",
      "teasing": "teasing playful demeanor",
    },
  },

  scenario: {
    cast_size: {
      "solo": "solo scene, alone",
      "duo": "two women together in scene",
      "threesome": "threesome, three people in scene",
      "foursome": "foursome, four people",
      "group": "group scene, multiple people",
      "gangbang": "gangbang scene, one woman surrounded by multiple men",
      "orgy": "full orgy scene, many people",
    },
    cast_type: {
      "twins": "two identical twin sisters, matching appearances, mirror images",
      "identical twins": "identical twin sisters, exactly matching, side by side",
      "sisters": "two sisters together, family resemblance",
      "best friends": "two best friends together",
      "roommates": "two roommates together",
      "mother and daughter": "MILF mother and adult daughter roleplay, older and younger woman, family resemblance",
      "stepmom and stepdaughter": "stepmom and adult stepdaughter roleplay, mature and young",
      "aunt and niece": "hot aunt and adult niece roleplay, mature and young",
      "grandma and granddaughter": "sexy granny and adult granddaughter roleplay, mature GILF and young",
      "milf granny": "sexy MILF granny, mature older woman",
      "mature and young": "mature older woman and young adult, age contrast",
      "teacher and student": "teacher and adult student roleplay",
      "boss and secretary": "boss and secretary roleplay",
      "nurse and patient": "nurse and patient roleplay",
      "coach and athlete": "coach and athlete roleplay",
      "dominant and submissive": "dominant and submissive pairing, dom and sub",
      "wife and mistress": "wife and mistress pairing",
    },
    roleplay: {
      "girl next door": "innocent girl-next-door character",
      "sexy stepmom": "sexy stepmom MILF character, mature seductress",
      "hot aunt": "hot aunt MILF character",
      "sexy granny": "sexy GILF granny character, mature grandmother",
      "milf": "MILF character, mature confident mother figure",
      "cougar": "cougar MILF, older woman seducing younger",
      "sugar mommy": "sugar mommy character, wealthy older seductress",
      "lonely housewife": "lonely bored housewife character, needy",
      "trophy wife": "gold-digger trophy wife character",
      "best friend's mom": "best friend's hot mom character",
      "step-sister": "step-sister character",
      "schoolgirl": "sexy schoolgirl character, innocent naughty",
      "college coed": "college coed character",
      "sorority girl": "sorority girl character",
      "cheerleader": "hot cheerleader character",
      "librarian": "naughty librarian character",
      "teacher": "sexy teacher character",
      "secretary": "sexy secretary character",
      "boss lady": "dominant boss lady character",
      "nurse": "naughty nurse character",
      "doctor": "sexy female doctor character",
      "yoga instructor": "sexy yoga instructor character",
      "personal trainer": "sexy fitness trainer character",
      "maid": "sexy French maid character",
      "waitress": "sexy waitress character",
      "flight attendant": "sexy flight attendant character",
      "dominatrix": "strict dominatrix character",
      "submissive": "obedient submissive character",
      "gothic girl": "gothic goth girl character, dark alternative",
      "e-girl": "e-girl character, alternative internet aesthetic",
      "onlyfans model": "OnlyFans model character",
      "cam girl": "webcam girl character",
      "porn star": "professional pornstar character",
    },
    acts: {
      "posing": "seductively posing for camera",
      "teasing": "teasing camera, slowly revealing, coy",
      "stripping": "mid-strip, undressing sensually",
      "flashing": "flashing pussy or tits at camera",
      "upskirt": "upskirt view, panties visible under skirt",
      "exposed": "fully exposed, nothing hidden",
      "spread eagle": "spread eagle position, legs and arms wide open, everything exposed",
      "spreading pussy": "using fingers to spread pussy lips open, holding lips apart",
      "masturbating": "solo masturbating, one hand between legs, fingers on clit, self-pleasuring",
      "fingering": "fingering own pussy, fingers inside vagina",
      "using dildo": "using a large dildo, pussy penetrated by sex toy",
      "using vibrator": "using a vibrator on clit, buzzing sex toy",
      "using rabbit": "using a rabbit vibrator on pussy and clit",
      "riding toy": "riding a huge dildo, straddling sex toy",
      "oral": "receiving oral sex, being eaten out, mouth on pussy",
      "blowjob": "giving a blowjob, mouth wrapped around cock, sucking eagerly",
      "deepthroat": "deepthroating cock, all the way down throat, gagging drool",
      "throatpie": "throatpie, cum shot deep in throat",
      "titfucking": "titfucking, cock between big breasts, sliding between tits",
      "handjob": "giving a handjob, hand stroking cock",
      "missionary": "having sex in missionary position, on back, legs up, being penetrated",
      "cowgirl": "riding on top cowgirl style, straddling and bouncing on cock",
      "reverse cowgirl": "reverse cowgirl, riding facing away, back arched, ass bouncing",
      "doggy style": "being fucked doggy style from behind, on all fours, hips gripped",
      "prone bone": "prone bone position, face down flat on stomach being fucked from behind",
      "spooning": "spooning sex position, side by side penetration",
      "standing sex": "standing sex position, leg raised, being fucked while standing",
      "against wall": "sex against wall, pinned and fucked against wall",
      "table sex": "having sex on a table, bent over table being fucked",
      "bent over": "bent over being fucked from behind, ass in the air",
      "legs on shoulders": "legs on partner's shoulders, deep penetration",
      "amazon position": "amazon position, riding on top with legs squatting over him",
      "anal": "anal sex, cock deep in tight asshole, being penetrated anally",
      "anal doggy": "anal doggy style, taking cock in ass from behind",
      "anal reverse cowgirl": "anal reverse cowgirl, riding cock in ass",
      "double penetration": "double penetration, one cock in pussy and one in ass simultaneously",
      "DAP": "double anal penetration, two cocks in ass",
      "DVP": "double vaginal penetration, two cocks in pussy",
      "DP": "DP double penetration, cocks in both holes",
      "facesitting": "facesitting, pussy on face, smothering partner",
      "sixty-nine": "sixty-nine position, mutual oral",
      "eating pussy": "eating pussy, tongue in vagina, licking labia",
      "rimming": "rimming asshole, tongue in ass",
      "lesbian": "lesbian scene, two women together",
      "tribbing": "tribbing, scissoring pussy against pussy",
      "scissoring": "scissoring, pussies pressed together, grinding",
      "strap-on": "using a strap-on dildo, wearing harness",
      "creampie": "creampie, cum dripping out of pussy, freshly filled full of cum",
      "cumshot": "cumshot, ropes of cum, ejaculation captured",
      "facial": "facial cumshot, cum on face, semen on cheeks lips and forehead",
      "bukkake": "bukkake scene, multiple cumshots covering face and body",
      "cum on tits": "cum on tits, semen dripping down breasts",
      "cum on ass": "cum on ass, semen dripping down butt cheeks",
      "cum on face": "cum on face, big load on cheeks and lips",
      "swallowing": "swallowing cum, cum in mouth being swallowed",
      "squirting": "squirting orgasm, streams of female ejaculation, pussy squirting fluid",
      "fisting": "fisting, fist inserted in pussy",
      "fisting deep": "deep fisting, arm inserted up to wrist and beyond",
      "double fisting": "double fisting, two fists worked into pussy",
      "fisting anal": "anal fisting, fist worked into ass",
      "prolapse": "prolapsed hole from extreme stretching",
      "gaping": "gaping open hole, pussy or ass stretched wide and gaping",
      "gaping wide": "extremely gaping wide-open hole, ring of pleasure",
      "stretched": "stretched hole, ring of pleasure",
      "stretched hole": "visibly stretched loose fuck-hole",
      "object insertion": "large object inserted, unusual insertion play",
      "bottle insertion": "bottle inserted into pussy, glass insertion play",
      "throat-fuck": "throat-fucked hard, cock deep down throat",
      "gagging": "gagging on cock, throat convulsing",
      "choking hands on throat": "hands wrapped around throat, being choked mid-fuck",
      "hair pulled hard": "hair pulled back hard mid-fuck, head yanked",
      "slapped mid-fuck": "slapped across the face during sex",
      "face-slapped": "face-slapped, red handprint on cheek",
      "hate-fuck framing": "hate-fuck framing, roughly used and discarded",
      "snowballing": "snowballing cum from mouth to mouth",
      "cum-sharing kiss": "cum-sharing kiss, mouths open with cum between",
      "cum swap": "swapping cum back and forth between mouths",
      "cum drool": "drooling cum out of mouth",
      "cum gargle": "gargling cum in the throat",
      "bukkake shower": "shower of cum from multiple partners, bukkake finale",
      "cum drenched": "drenched in cum from head to feet",
      "cnc roleplay": "consensual non-consent roleplay, staged struggle",
      "captured": "captured captive scenario, held against will roleplay",
      "tentacle": "tentacle sex, tendrils wrapped around body",
      "monster": "monster sex, inhuman partner",
      "alien": "alien sex, otherworldly encounter",
      "breeding kink": "breeding kink, being bred and filled",
      "impregnation kink": "impregnation kink, made pregnant fantasy",
      "pregnancy belly": "visibly pregnant belly during sex",
      "ahegao mid-cum": "ahegao expression at moment of orgasm",
      "mind-broken": "mind-broken, fucked into blankness",
      "bondage": "in bondage, restrained and tied up",
      "shibari": "elaborate shibari rope bondage, intricate kinbaku ties",
      "tied up": "tied up with rope, wrists and ankles bound",
      "collared and leashed": "wearing collar and leash, held submissively",
      "spanking": "being spanked, red handprints on ass cheeks",
      "gagged": "ball gagged, drool dripping from mouth",
    },
  },

  scene: {
    environment: {
      "studio": "professional photography studio, seamless backdrop",
      "beach": "tropical beach, ocean waves, sand, sunset",
      "forest": "misty forest, tall trees, natural lighting",
      "urban street": "urban city street, night lights, neon signs",
      "rooftop": "high-rise rooftop, city skyline background",
      "bedroom": "luxury bedroom, silk sheets, king bed, romantic",
      "warehouse": "abandoned industrial warehouse, gritty",
      "desert": "vast desert landscape, sand dunes, dramatic sky",
      "neon alley": "neon-lit alley, cyberpunk atmosphere, wet reflective ground",
      "castle": "medieval stone castle interior, torch-lit",
    },
    era: {
      "80s": "1980s retro aesthetic, big hair, neon",
      "90s": "1990s aesthetic, minimalist grunge",
      "vintage": "vintage retro aesthetic, film photography style",
      "futuristic": "futuristic sci-fi aesthetic",
      "medieval": "medieval fantasy aesthetic",
      "victorian": "victorian era aesthetic, corsets and lace",
      "cyberpunk": "cyberpunk neon-noir aesthetic",
    },
  },

  lighting: {
    source: {
      "natural": "natural sunlight, golden warm light",
      "window": "soft window light streaming in",
      "softbox": "professional softbox studio lighting, even soft light",
      "hard key": "hard directional key light, dramatic shadows",
      "neon": "colorful neon lighting, purple pink cyan glow",
      "candle": "warm candlelight, flickering intimate glow",
      "firelight": "warm firelight, flickering orange glow",
      "moonlight": "soft cool moonlight",
    },
    style: {
      "cinematic": "cinematic lighting, film-like quality",
      "chiaroscuro": "dramatic chiaroscuro lighting, high contrast between light and shadow",
      "high-key": "high-key bright even lighting",
      "low-key": "low-key moody dark lighting with selective highlights",
      "golden hour": "golden hour warm sunset lighting",
      "blue hour": "blue hour twilight lighting",
      "hard shadows": "hard defined shadows, dramatic light falloff",
    },
    mood: {
      "dramatic": "dramatic moody atmosphere",
      "soft": "soft romantic atmosphere",
      "moody": "moody dark atmosphere",
      "sensual": "deeply sensual erotic atmosphere",
      "harsh": "harsh unforgiving lighting",
    },
  },

  camera: {
    lens: {
      "24mm": "24mm wide angle lens",
      "35mm": "35mm lens, natural perspective",
      "50mm": "50mm nifty-fifty lens, natural perspective",
      "85mm": "85mm portrait lens, beautiful bokeh",
      "135mm": "135mm telephoto portrait lens, compressed perspective",
      "macro": "macro lens, extreme detail",
    },
    aperture: {
      "f/1.4": "shot at f/1.4, extremely shallow depth of field, creamy bokeh",
      "f/1.8": "shot at f/1.8, shallow depth of field",
      "f/2.8": "shot at f/2.8, moderate depth of field",
    },
  },

  style: {
    render: {
      "photorealistic": "photorealistic, ultra-detailed, hyperrealistic photography",
      "cinematic": "cinematic film-like quality, movie still",
      "analog film": "analog 35mm film photography, film grain, kodak portra",
      "editorial": "editorial fashion photography style, high-end magazine quality",
      "documentary": "documentary photojournalism style, candid",
      "35mm film": "35mm film photograph, grainy analog quality",
    },
    artistic_tone: {
      "moody": "moody dark tonal grading",
      "vibrant": "vibrant saturated colors",
      "desaturated": "desaturated muted color palette",
      "high-contrast": "high contrast, punchy",
      "faded": "faded vintage tone, washed out",
    },
  },
};

// Optional per-phrase graphic-vernacular overrides. Applied when a shot is set to Raunch mode.
// Only overrides where explicitly listed — everything else falls through to PROMPT_MAP.
export const RAUNCH_MAP = {
  intimate: {
    pussy: {
      "wet": "sopping wet fucked-open pussy, dripping cunt, soaked slit",
      "spread": "spread-open cunt, gaping wide pussy hole, everything on display",
      "meaty": "meaty fuck-hole, thick juicy cunt lips",
      "puffy": "puffy fuck-me cunt, swollen used pussy",
    },
    nipples: {
      "erect": "rock-hard fuck-me nipples, throbbing tips begging to be sucked",
      "puffy": "swollen puffy suck-my-tits nipples",
    },
    cum_state: {
      "fresh creampie": "freshly bred, thick load pumped deep in her cunt",
      "dripping creampie": "cum leaking out of her used fucked-open pussy",
      "gaping creampie": "gaping stretched cunt with cum pouring out",
      "cum on face": "load of cum splattered across her slutty face",
      "cum-covered whole body": "drenched in cum from head to tits, soaked in cock juice",
    },
  },
  scenario: {
    acts: {
      "blowjob": "sucking cock like a hungry slut, lips around a hard dick",
      "deepthroat": "taking every inch down her throat, gagging on cock, drooling",
      "doggy style": "getting fucked doggy style hard from behind, ass raised like a bitch in heat",
      "creampie": "bred and filled with cum, load pumped deep in her cunt",
      "cumshot": "getting a huge load blasted on her, ropes of cum",
      "facial": "cum splattered all over her slutty face",
      "bukkake": "gangbanged and painted in cum, load after load on her face",
      "gaping": "gaping stretched-out fuck-hole",
      "throat-fuck": "throat used like a fuck-hole, gagging and drooling",
      "hate-fuck framing": "used and hate-fucked like a piece of meat",
      "mind-broken": "fucked into mindless slut-space, brain melted from cock",
    },
    roleplay: {
      "milf": "slutty MILF, cock-hungry mom",
      "onlyfans model": "OnlyFans whore, camera-loving slut",
      "porn star": "professional cum-slut, pornstar bitch",
    },
  },
  kink: {
    humiliation: {
      "wrecked": "wrecked and ruined like a used slut",
      "used": "used up like a fuck-toy",
      "slut-face": "slutty fucked-dumb face, cum-drunk expression",
      "ahegao expression": "ahegao slut-face, eyes rolled back, tongue out, cock-drunk",
    },
  },
};

export function expandPrompt(section, field, value, opts = {}) {
  if (!value) return "";
  if (opts.raunch) {
    const raunch = RAUNCH_MAP?.[section]?.[field]?.[value];
    if (raunch) return raunch;
  }
  const mapped = PROMPT_MAP?.[section]?.[field]?.[value];
  return mapped || value;
}
